---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  skip:
    - prettier
    # Because these are local hooks it seems like they won't easily run in pre-commit CI
    - eslint
    - style-lint
    - hadolint-docker
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ".hbs$"
      - id: check-yaml
      - id: check-added-large-files
        exclude: "yarn.lock|.yarn/releases/.*|frontend-demo/.yarn/releases/.*"
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier --write
        language: node
        types_or:
          [javascript, jsx, ts, tsx, json, scss, sass, css, yaml, markdown]
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.10.0-1
    hooks:
      - id: shfmt
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--format, parsable, -d, relaxed]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args:
          - --baseline
          - .secrets.baseline
          - --exclude-files
          - .yarn/
          - --exclude-files
          - cassettes/
          - --exclude-files
          - test_json/
          - --exclude-files
          - ".*_test.py"
          - --exclude-files
          - "test_.*.py"
          - --exclude-files
          - poetry.lock
          - --exclude-files
          - yarn.lock
          - --exclude-files
          - ".*/generated/"
          - --exclude-files
          - "config/keycloak/tls/*"
          - --exclude-files
          - "config/keycloak/realms/default-realm.json"
        additional_dependencies: ["gibberish-detector"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.7.2"
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--extend-ignore=D1, --fix]
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        description: "Lint JS/TS files and apply automatic fixes"
        entry: npm exec --prefix frontend-demo -- eslint --fix --config frontend-demo/.eslintrc.js
        language: node
        types_or: [javascript, jsx, ts, tsx]
        args: []
        exclude: "(node_modules/|.yarn/)"
        require_serial: false
        additional_dependencies:
          - eslint@8
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
