services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 1gb
    cpus: 2
    command: ./scripts/run-django-dev.sh
    stdin_open: true
    tty: true
    ports:
      - "8001:8001"
      - "8888:8888"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/src
      - ../open-learning-ai-tutor:/open-learning-ai-tutor
      - django_media:/var/media

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      /bin/bash -c '
      sleep 3;
      celery -A main.celery:app worker -E -Q default,edx_content -B -l ${MITOL_LOG_LEVEL:-INFO}'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/src
      - ../open-learning-ai-tutor:/open-learning-ai-tutor
      - django_media:/var/media

  watch:
    working_dir: /src
    image: node:22.19
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        yarn install
        yarn start
    ports:
      - "8003:8003"
      - "8004:8004"
    volumes:
      - ./frontend-demo:/src
