include:
  - docker-compose.services.yml

services:
  web:
    extends:
      file: docker-compose.apps.yml
      service: web
    env_file:
      - path: env/backend.env
      - path: env/backend.local.env
        required: false
      # DEPRECATED: legacy .env file at the repo root
      - path: .env
        required: false

  celery:
    extends:
      file: docker-compose.apps.yml
      service: celery
    env_file:
      - path: env/backend.env
      - path: env/backend.local.env
        required: false
      # DEPRECATED: legacy .env file at the repo root
      - path: .env
        required: false
