"""Typed django-aqueduct settings model for main.settings.

This file was generated by:
    python manage.py generate_aqueduct_settings --modules main.settings \\
        --output main/aqueduct_settings.py
...and then hand-refined to restore fields that the generator could not
infer purely from a runtime snapshot of main.settings:

- Required fields (no sane default in main/settings.py, which raises
#   ImproperlyConfigured when unset): APP_BASE_URL, MAILGUN_SENDER_DOMAIN,
  MAILGUN_KEY, MITOL_COOKIE_NAME, MITOL_COOKIE_DOMAIN.
- Values derived from other settings/env vars at import time in
  main/settings.py (DATABASES, STATIC_URL, MIDDLEWARE/INSTALLED_APPS,
  CELERY_BEAT_SCHEDULE, FEATURES, ANYMAIL, JWT_AUTH, CHANNEL_LAYERS,
  CELERY_BROKER_URL, the AI_DEFAULT_*_MODEL family) are recomputed in
  model_validators below rather than left as generation-time snapshots.
- Machine/host-specific values baked in by the generator at the moment it
  ran (BASE_DIR, STATICFILES_DIRS, TEMPLATES DIRS, HOSTNAME) are rebuilt
  dynamically instead.

Known gaps (not modeled -- see the README for details):

- ADMINS is derived from ADMIN_EMAIL in main/settings.py; not re-derived
  here, override ADMINS directly if you need admin email notifications.
- STORAGES / the MITOL_USE_S3 validation block is not modeled; set
  STORAGES explicitly if you enable MITOL_USE_S3.
- LOGGING is intentionally NOT a field on this model -- it's imported
  directly from mitol.observability.settings.logging in the settings
  shim modules (main/settings_aqueduct.py, main/settings_aqueduct_dev.py),
  matching how main/settings.py does it.
"""

from __future__ import annotations

import datetime
import os
import pathlib
import platform
from typing import Any
from urllib.parse import urljoin

import dj_database_url
from celery.schedules import crontab
from pydantic import Field, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

from main.envs import get_bool

# main/aqueduct_settings.py lives alongside main/settings.py, so this
# mirrors main.settings.BASE_DIR's two-levels-up-from-this-file computation.
_PROJECT_ROOT = pathlib.Path(__file__).resolve().parent.parent


class AqueductSettings(BaseSettings):
    """Typed Django settings model.

    Populate from environment variables, YAML, Vault, AWS SSM, or any
    combination by configuring ``model_config`` and the sources below.
    """

    model_config = SettingsConfigDict(
        env_prefix="",
        extra="allow",
    )

    # ===== main.settings =====
    ADMINS: tuple[Any, ...] = Field(default=())  # populated by _configure_admins below
    ADMIN_EMAIL: str = Field(default="", validation_alias="MITOL_ADMIN_EMAIL")
    AI_ANON_LIMIT_MULTIPLIER: float = Field(default=10.0)
    AI_BUDGET_DURATION: str = Field(default="60m")
    AI_CHATBOTS_COOKIE_MAX_AGE: int = Field(default=604800)
    AI_CHATBOTS_SESSION_EXPIRY_DAYS: int = Field(default=36500)
    AI_CITED_PROMPTS: list[Any] = Field(default_factory=list)
    AI_DEBUG: bool = Field(default=False)
    AI_DEFAULT_MODEL: str = Field(default="openai/gpt-4o-mini")
    AI_DEFAULT_RECOMMENDATION_MAX_TOKENS: int = Field(default=7500)
    # AI_DEFAULT_RECOMMENDATION_MODEL/SUMMARY_MODEL/SYLLABUS_MODEL/VIDEO_GPT_MODEL
    # default from AI_DEFAULT_MODEL when not explicitly set; see
    # _configure_ai_model_defaults below.
    AI_DEFAULT_RECOMMENDATION_MODEL: str = Field(default="openai/gpt-4o-mini")
    AI_DEFAULT_SUMMARY_MODEL: str = Field(default="openai/gpt-4o-mini")
    AI_DEFAULT_SYLLABUS_MAX_TOKENS: int = Field(default=16384)
    AI_DEFAULT_SYLLABUS_MODEL: str = Field(default="openai/gpt-4o-mini")
    AI_DEFAULT_TEMPERATURE: float = Field(default=0.1)
    AI_DEFAULT_TUTOR_MODEL: str = Field(default="openai/gpt-4o")
    AI_DEFAULT_VIDEO_GPT_MAX_TOKENS: int = Field(default=16384)
    AI_DEFAULT_VIDEO_GPT_MODEL: str = Field(default="openai/gpt-4o-mini")
    AI_HUMAN_MAX_CONVERSATION_MEMORY: int = Field(default=6)
    AI_INVERSE_METRICS: list[Any] = Field(
        default_factory=lambda: ["hallucination", "hallucinationmetric"]
    )
    AI_MAX_BUDGET: float = Field(default=0.05)
    AI_MAX_MESSAGE_LENGTH: int = Field(default=6000)
    AI_MAX_PARALLEL_REQUESTS: int = Field(default=10)
    AI_MAX_TOKEN_BIND: int = Field(default=16384)
    AI_MIT_CONTENTFILE_URL: str = Field(
        default="https://api.learn.mit.edu/api/v1/contentfiles/"
    )
    AI_MIT_CONTENT_SEARCH_LIMIT: int = Field(default=10)
    AI_MIT_SEARCH_DETAIL_URL: str = Field(default="https://learn.mit.edu/?resource=")
    AI_MIT_SEARCH_ELASTIC_URL: str = Field(
        default="https://api.learn.mit.edu/api/v1/learning_resources_search/"
    )
    AI_MIT_SEARCH_LIMIT: int = Field(default=10)
    # AI_MIT_SEARCH_URL defaults from AI_MIT_SEARCH_VECTOR_URL when not
    # explicitly set; see _configure_ai_model_defaults below.
    AI_MIT_SEARCH_URL: str = Field(
        default="https://api.learn.mit.edu/api/v0/vector_learning_resources_search/"
    )
    AI_MIT_SEARCH_VECTOR_URL: str = Field(
        default="https://api.learn.mit.edu/api/v0/vector_learning_resources_search/"
    )
    AI_MIT_SYLLABUS_URL: str = Field(
        default="https://api.learn.mit.edu/api/v0/vector_content_files_search/"
    )
    # Reads the same env var as AI_MIT_CONTENT_SEARCH_LIMIT, matching a
    # pre-existing quirk in main/settings.py (not something introduced here).
    AI_MIT_TRANSCRIPT_SEARCH_LIMIT: int = Field(
        default=5, validation_alias="AI_MIT_CONTENT_SEARCH_LIMIT"
    )
    AI_MIT_VIDEO_TRANSCRIPT_URL: str = Field(
        default="https://api.learn.mit.edu/api/v0/vector_content_files_search/"
    )
    AI_PROMPT_CACHE_DURATION: int = Field(default=2419200)
    AI_PROMPT_CACHE_FUNCTION: str = Field(default="ai_chatbots.utils.get_django_cache")
    AI_PROXY_AUTH_TOKEN: str = Field(default="")
    AI_PROXY_CLASS: str = Field(default="")
    AI_PROXY_URL: str = Field(default="")
    AI_RPM_LIMIT: int = Field(default=10)
    AI_TPM_LIMIT: int = Field(default=5000)
    AI_TUTOR_MAX_CONVERSATION_MEMORY: int = Field(default=6)
    ALLOWED_HOSTS: list[Any] = Field(default_factory=lambda: ["*"])
    # NOTE: type intentionally loose, matches settings.py's untyped value
    ANONYMOUS_USER_NAME: Any = Field(default=None)
    # ANYMAIL is derived from MAILGUN_KEY/MAILGUN_SENDER_DOMAIN; see
    # _configure_anymail below.
    ANYMAIL: dict[str, Any] = Field(default_factory=dict)
    APISIX_USERDATA_MAP: dict[str, Any] = Field(
        default_factory=lambda: {
            "users_user": {
                "email": "email",
                "global_id": "sub",
                "username": "preferred_username",
                "name": "name",
            },
            "users_userprofile": {"country_code": None},
        }
    )
    # Required: main.settings raises ImproperlyConfigured if this is unset.
    APP_BASE_URL: str = Field(validation_alias="MITOL_APP_BASE_URL")
    ASGI_APPLICATION: str = Field(default="main.asgi.application")
    # NOTE: type intentionally loose, matches settings.py's untyped value
    AUTHENTICATION_BACKENDS: tuple[Any, ...] = Field(
        default=(
            "django.contrib.auth.backends.ModelBackend",
            "guardian.backends.ObjectPermissionBackend",
        )
    )
    AUTH_USER_MODEL: str = Field(default="users.User")
    AWS_ACCESS_KEY_ID: bool = Field(default=False)
    AWS_QUERYSTRING_AUTH: bool = Field(default=False)
    AWS_SECRET_ACCESS_KEY: bool = Field(default=False)
    AWS_STORAGE_BUCKET_NAME: bool = Field(default=False)
    # BASE_DIR mirrors main.settings.BASE_DIR: computed from this file's
    # location rather than baked in at generation time.
    BASE_DIR: str = Field(default_factory=lambda: str(_PROJECT_ROOT))
    CACHES: dict[str, Any] = Field(
        default_factory=lambda: {
            "default": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
                "LOCATION": "local-in-memory-cache",
            },
            "external_assets": {
                "BACKEND": "django.core.cache.backends.db.DatabaseCache",
                "LOCATION": "external_asset_cache",
            },
            "durable": {
                "BACKEND": "django.core.cache.backends.db.DatabaseCache",
                "LOCATION": "durable_cache",
            },
            "redis": {
                "BACKEND": "django_redis.cache.RedisCache",
                # LOCATION is patched to the resolved CELERY_BROKER_URL in
                # _configure_redis_broker below.
                "LOCATION": None,
                "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
            },
        }
    )
    CANVAS_SYLLABUS_DEMO_READABLE_IDS: list[Any] = Field(default_factory=list)
    CANVAS_TUTOR_DEMO_RUN_READABLE_IDS: list[Any] = Field(default_factory=list)
    # CELERY_BEAT_SCHEDULE holds celery.schedules.crontab objects, which
    # aren't natively serialisable; it's rebuilt in
    # _configure_celery_beat_schedule below rather than kept as a plain
    # default.
    CELERY_BEAT_SCHEDULE: dict[str, Any] = Field(default_factory=dict)
    # CELERY_BROKER_URL falls back to REDIS_URL (which itself falls back to
    # REDISCLOUD_URL) when not explicitly set; see _configure_redis_broker.
    CELERY_BROKER_URL: str | None = Field(default=None)
    CHANNEL_LAYERS: dict[str, Any] = Field(default_factory=dict)
    CLOUDFRONT_DIST: str | None = Field(default=None)
    CONSUMER_THROTTLE_CLASSES: list[Any] = Field(
        default_factory=lambda: ["main.consumer_throttles.UserScopedRateThrottle"]
    )
    CORS_ALLOWED_ORIGINS: list[Any] = Field(default_factory=list)
    CORS_ALLOWED_ORIGIN_REGEXES: list[Any] = Field(default_factory=list)
    CORS_ALLOW_CREDENTIALS: bool = Field(default=True)
    # NOTE: type intentionally loose, matches settings.py's untyped value
    CORS_ALLOW_HEADERS: tuple[Any, ...] = Field(
        default=(
            "accept",
            "authorization",
            "content-type",
            "user-agent",
            "x-csrftoken",
            "x-requested-with",
            "baggage",
            "sentry-trace",
        )
    )
    CORS_ALLOW_METHODS: list[Any] = Field(default_factory=lambda: ["POST", "OPTIONS"])
    CORS_ALLOW_ORIGINS: list[Any] = Field(default_factory=list)
    # NOTE: type intentionally loose, matches settings.py's untyped value
    CSRF_COOKIE_DOMAIN: Any = Field(default=None)
    CSRF_COOKIE_NAME: str = Field(default="csrftoken")
    CSRF_COOKIE_SECURE: bool = Field(default=True)
    CSRF_HEADER_NAME: str = Field(default="HTTP_X_CSRFTOKEN")
    CSRF_TRUSTED_ORIGINS: list[Any] = Field(default_factory=list)
    # DATABASES/DEFAULT_DATABASE_CONFIG are derived from DATABASE_URL,
    # MITOL_DB_CONN_MAX_AGE, and MITOL_DB_DISABLE_SSL; see
    # _configure_database below.
    DATABASES: dict[str, Any] = Field(default_factory=dict)
    # DATABASE_URL is not a top-level name in main.settings (only used
    # inline when building DEFAULT_DATABASE_CONFIG), so the generator could
    # not discover it; added by hand with the same sqlite fallback.
    DATABASE_URL: str = Field(
        default_factory=lambda: f"sqlite:///{_PROJECT_ROOT / 'db.sqlite3'}"
    )
    DEBUG: bool = Field(default=False)
    DEFAULT_AUTO_FIELD: str = Field(default="django.db.models.AutoField")
    DEFAULT_DATABASE_CONFIG: dict[str, Any] = Field(default_factory=dict)
    DEFAULT_FROM_EMAIL: str = Field(
        default="webmaster@localhost", validation_alias="MITOL_FROM_EMAIL"
    )
    EMAIL_BACKEND: str = Field(
        default="django.core.mail.backends.smtp.EmailBackend",
        validation_alias="MITOL_EMAIL_BACKEND",
    )
    EMAIL_HOST: str = Field(default="localhost", validation_alias="MITOL_EMAIL_HOST")
    EMAIL_HOST_PASSWORD: str = Field(
        default="", validation_alias="MITOL_EMAIL_PASSWORD"
    )
    EMAIL_HOST_USER: str = Field(default="", validation_alias="MITOL_EMAIL_USER")
    EMAIL_PORT: int = Field(default=25, validation_alias="MITOL_EMAIL_PORT")
    EMAIL_SUPPORT: str = Field(
        default="support@example.com", validation_alias="MITOL_SUPPORT_EMAIL"
    )
    EMAIL_USE_TLS: bool = Field(default=False, validation_alias="MITOL_EMAIL_TLS")
    EMBEDLY_EMBED_URL: str = Field(default="https://api.embed.ly/1/oembed")
    # Reads the same env var as EMBEDLY_EMBED_URL, matching a pre-existing
    # quirk in main/settings.py (not something introduced here).
    EMBEDLY_EXTRACT_URL: str = Field(
        default="https://api.embed.ly/1/extract",
        validation_alias="EMBEDLY_EMBED_URL",
    )
    # NOTE: type intentionally loose, matches settings.py's untyped value
    EMBEDLY_KEY: Any = Field(default=None)
    ENVIRONMENT: str = Field(default="dev", validation_alias="MITOL_ENVIRONMENT")
    EXTERNAL_MODELS: list[Any] = Field(default_factory=lambda: ["programcertificate"])
    # FEATURES scans os.environ for MITOL_FEATURES_PREFIX-prefixed keys at
    # validation time, matching main.settings' get_all_config_keys() scan;
    # see _configure_features below.
    FEATURES: dict[str, Any] = Field(default_factory=dict)
    GA_G_TRACKING_ID: str = Field(default="")
    GA_TRACKING_ID: str = Field(default="")
    HEALTH_CHECK: dict[str, Any] = Field(
        default_factory=lambda: {
            "SUBSETS": {
                "startup": [
                    "health_check.backends.MigrationsHealthCheck",
                    "health_check.cache.CacheBackend",
                    "health_check.backends.DatabaseBackend",
                ],
                "liveness": ["health_check.backends.DatabaseBackend"],
                "readiness": [
                    "health_check.cache.CacheBackend",
                    "health_check.backends.DatabaseBackend",
                ],
                "full": [
                    "health_check.backends.MigrationsHealthCheck",
                    "health_check.cache.CacheBackend",
                    "health_check.backends.DatabaseBackend",
                ],
            }
        }
    )
    HIJACK_ALLOW_GET_REQUESTS: bool = Field(default=True)
    HIJACK_LOGOUT_REDIRECT_URL: str = Field(default="/admin/auth/user")
    # HOST_IP is not a top-level name in main.settings (only used inline to
    # build INTERNAL_IPS), so the generator could not discover it; added by
    # hand. See _configure_internal_ips below.
    HOST_IP: str = Field(default="127.0.0.1")
    # HOSTNAME mirrors main.settings.HOSTNAME: computed at instantiation
    # time rather than baked in from the machine that ran the generator.
    HOSTNAME: str = Field(default_factory=lambda: platform.node().split(".")[0])
    INSTALLED_APPS: tuple[str, ...] = Field(
        default=(
            "django.contrib.admin",
            "django.contrib.auth",
            "django.contrib.contenttypes",
            "django.contrib.sessions",
            "django.contrib.messages",
            "django.contrib.staticfiles",
            "django.contrib.humanize",
            "django.contrib.sites",
            "django_filters",
            "django_scim",
            "rest_framework",
            "drf_spectacular",
            "oauth2_provider",
            "server_status",
            "anymail",
            "hijack",
            "hijack.contrib.admin",
            "guardian",
            "channels",
            "mitol.observability.apps.ObservabilityConfig",
            "main",
            "openapi",
            "users",
            "ai_chatbots",
            "health_check",
            "health_check.cache",
        )
    )
    # NOTE: type intentionally loose, matches settings.py's untyped value
    # INTERNAL_IPS is derived from HOST_IP; see _configure_internal_ips below.
    INTERNAL_IPS: tuple[Any, ...] = Field(default=("127.0.0.1",))
    # JWT_AUTH is derived from MITOL_JWT_SECRET/MITOL_COOKIE_NAME; see
    # _configure_jwt_auth below.
    JWT_AUTH: dict[str, Any] = Field(default_factory=dict)
    KEYCLOAK_ADMIN_CLIENT_ID: bool = Field(default=False)
    KEYCLOAK_ADMIN_CLIENT_SECRET: bool = Field(default=False)
    KEYCLOAK_ADMIN_SECURE: bool = Field(default=True)
    KEYCLOAK_ADMIN_URL: bool = Field(default=False)
    KEYCLOAK_BASE_URL: str = Field(default="http://mit-keycloak-base-url.edu")
    KEYCLOAK_REALM: bool = Field(default=False)
    KEYCLOAK_REALM_NAME: str = Field(default="olapps")
    # NOTE: type intentionally loose, matches settings.py's untyped value
    LANGSMITH_API_KEY: Any = Field(default=None)
    LANGUAGE_CODE: str = Field(default="en-us")
    LEARN_ACCESS_TOKEN: str = Field(default="")
    # NOTE: type intentionally loose, matches settings.py's untyped value
    MAILGUN_BCC_TO_EMAIL: Any = Field(default=None)
    MAILGUN_FROM_EMAIL: str = Field(default="no-reply@example.com")
    # Required: main.settings raises ImproperlyConfigured if this is unset.
    MAILGUN_KEY: str
    # NOTE: type intentionally loose, matches settings.py's untyped value
    MAILGUN_RECIPIENT_OVERRIDE: Any = Field(default=None)
    # Required: main.settings raises ImproperlyConfigured if this is unset.
    MAILGUN_SENDER_DOMAIN: str
    MEDIA_ROOT: str = Field(default="/var/media/")
    MEDIA_URL: str = Field(default="/media/")
    MIDDLEWARE: tuple[str, ...] = Field(
        default=(
            "django.middleware.security.SecurityMiddleware",
            "django.contrib.sessions.middleware.SessionMiddleware",
            "django.middleware.common.CommonMiddleware",
            "django.middleware.csrf.CsrfViewMiddleware",
            "django.contrib.auth.middleware.AuthenticationMiddleware",
            "main.middleware.apisix_user.ApisixUserMiddleware",
            "django.contrib.messages.middleware.MessageMiddleware",
            "django.middleware.clickjacking.XFrameOptionsMiddleware",
            "hijack.middleware.HijackUserMiddleware",
        )
    )
    MIDDLEWARE_FEATURE_FLAG_COOKIE_MAX_AGE_SECONDS: int = Field(default=3600)
    MIDDLEWARE_FEATURE_FLAG_COOKIE_NAME: str = Field(default="MITOL_FEATURE_FLAGS")
    # NOTE: type intentionally loose, matches settings.py's untyped value
    MIDDLEWARE_FEATURE_FLAG_QS_PREFIX: Any = Field(default=None)
    MIGRATION_MODULES: dict[str, Any] = Field(
        default_factory=lambda: {"data_fixtures": None}
    )
    # Required: main.settings raises ImproperlyConfigured if this is unset.
    MITOL_COOKIE_DOMAIN: str
    # Required: main.settings raises ImproperlyConfigured if this is unset.
    MITOL_COOKIE_NAME: str
    # MITOL_DB_CONN_MAX_AGE/MITOL_DB_DISABLE_SSL are not top-level names in
    # main.settings (only used inline building DEFAULT_DATABASE_CONFIG), so
    # the generator could not discover them; added by hand.
    MITOL_DB_CONN_MAX_AGE: int = Field(default=0)
    MITOL_DB_DISABLE_SSL: bool = Field(default=False)
    MITOL_FEATURES_DEFAULT: bool = Field(default=False)
    MITOL_FEATURES_PREFIX: str = Field(default="FEATURE_")
    MITOL_JWT_SECRET: str = Field(default="terribly_unsafe_default_jwt_secret_key")
    MITOL_TITLE: str = Field(default="MIT Learn")
    MITOL_UNSUBSCRIBE_TOKEN_MAX_AGE_SECONDS: int = Field(default=604800)
    MITOL_USE_S3: bool = Field(default=False)
    MIT_LEARN_API_PROXY_BASE_URL: str = Field(default="https://api.learn.mit.edu/api/")
    NOTIFICATION_ATTEMPT_CHUNK_SIZE: int = Field(default=100)
    NOTIFICATION_ATTEMPT_RATE_LIMIT: str = Field(default="600/m")
    NOTIFICATION_EMAIL_BACKEND: str = Field(
        default="anymail.backends.test.EmailBackend",
        validation_alias="MITOL_NOTIFICATION_EMAIL_BACKEND",
    )
    OPENAI_API_KEY: str = Field(default="")
    OPENTELEMETRY_BATCH_SIZE: int = Field(default=512)
    # NOTE: type intentionally loose, matches settings.py's untyped value
    OPENTELEMETRY_ENDPOINT: Any = Field(default=None)
    OPENTELEMETRY_EXPORT_TIMEOUT_MS: int = Field(default=5000)
    OPENTELEMETRY_INSECURE: bool = Field(default=True)
    OPENTELEMETRY_SERVICE_NAME: str = Field(default="learn-ai")
    POSTHOG_API_HOST: str = Field(default="https://us.posthog.com")
    # NOTE: type intentionally loose, matches settings.py's untyped value
    POSTHOG_PERSONAL_API_KEY: Any = Field(default=None)
    POSTHOG_PROJECT_API_KEY: str = Field(default="")
    # NOTE: type intentionally loose, matches settings.py's untyped value
    POSTHOG_PROJECT_ID: Any = Field(default=None)
    POSTHOG_TIMEOUT_MS: int = Field(default=3000)
    PROBLEM_SET_URL: str = Field(
        default="https://api.learn.mit.edu/api/v0/tutor/problems/"
    )
    QUERY_BATCH_SIZE: int = Field(default=500)
    REACT_GA_DEBUG: bool = Field(default=False)
    RECAPTCHA_SECRET_KEY: str = Field(default="")
    RECAPTCHA_SITE_KEY: str = Field(default="")
    # REDISCLOUD_URL is not a top-level name in main.settings (only used
    # inline as a fallback for REDIS_URL), so the generator could not
    # discover it; added by hand.
    REDISCLOUD_URL: str | None = Field(default=None)
    REDIS_DOMAIN: str = Field(default="redis://redis:6379/0")
    REDIS_HOST_PARAMS: dict[str, Any] = Field(default_factory=dict)
    REDIS_SSL_CERT_REQS: str | None = Field(default=None)
    # REDIS_URL falls back to REDISCLOUD_URL when not explicitly set; see
    # _configure_redis_broker below.
    REDIS_URL: str | None = Field(default=None)
    REQUESTS_KEEPALIVE_EXPIRY: int = Field(default=180)
    REQUESTS_TIMEOUT: int = Field(default=30)
    REST_FRAMEWORK: dict[str, Any] = Field(
        default_factory=lambda: {
            "DEFAULT_PERMISSION_CLASSES": (
                "rest_framework.permissions.IsAuthenticated",
            ),
            "DEFAULT_AUTHENTICATION_CLASSES": (
                "rest_framework.authentication.SessionAuthentication",
            ),
            "EXCEPTION_HANDLER": "main.exceptions.api_exception_handler",
            "TEST_REQUEST_DEFAULT_FORMAT": "json",
            "TEST_REQUEST_RENDERER_CLASSES": [
                "rest_framework.renderers.JSONRenderer",
                "rest_framework.renderers.MultiPartRenderer",
            ],
            "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
            "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.NamespaceVersioning",
            "ALLOWED_VERSIONS": ["v0"],
            "ORDERING_PARAM": "sortby",
        }
    )
    ROOT_URLCONF: str = Field(default="main.urls")
    SEARCH_PAGE_CACHE_DURATION: int = Field(default=86400)
    # Not required in main.settings -- restores the real default there
    # rather than a value picked up from this project's local dev env.
    SECRET_KEY: str = Field(default="terribly_unsafe_default_secret_key")
    SECURE_CROSS_ORIGIN_OPENER_POLICY: str = Field(default="same-origin")
    # NOTE: type intentionally loose, matches settings.py's untyped value
    SECURE_PROXY_SSL_HEADER: tuple[Any, ...] = Field(
        default=("HTTP_X_FORWARDED_PROTO", "https")
    )
    SECURE_REDIRECT_EXEMPT: list[Any] = Field(
        default_factory=lambda: [
            "^health/startup/$",
            "^health/liveness/$",
            "^health/readiness/$",
            "^health/full/$",
        ]
    )
    SECURE_SSL_REDIRECT: bool = Field(
        default=True, validation_alias="MITOL_SECURE_SSL_REDIRECT"
    )
    SENTRY_DSN: str = Field(default="")
    SENTRY_LOG_LEVEL: str = Field(default="ERROR")
    SENTRY_PROFILES_SAMPLE_RATE: float = Field(default=0)
    SENTRY_TRACES_SAMPLE_RATE: float = Field(default=0)
    # NOTE: type intentionally loose, matches settings.py's untyped value
    SESSION_COOKIE_DOMAIN: Any = Field(default=None)
    SESSION_COOKIE_NAME: str = Field(default="sessionid")
    SESSION_ENGINE: str = Field(
        default="django.contrib.sessions.backends.signed_cookies"
    )
    SITE_ID: int = Field(default=1)
    SPECTACULAR_SETTINGS: dict[str, Any] = Field(
        default_factory=lambda: {
            "TITLE": "Learn AI API",
            "DESCRIPTION": "MIT public API",
            "VERSION": "0.0.1",
            "SERVE_INCLUDE_SCHEMA": False,
            "SERVE_URLCONF": "main.urls",
            "ENUM_GENERATE_CHOICE_DESCRIPTION": True,
            "COMPONENT_SPLIT_REQUEST": True,
            "AUTHENTICATION_WHITELIST": [],
            "SCHEMA_PATH_PREFIX": "/api/v[0-9]",
            "POSTPROCESSING_HOOKS": [
                "openapi.hooks.add_channels_routes",
                "drf_spectacular.hooks.postprocess_schema_enums",
                "openapi.hooks.postprocess_x_enum_descriptions",
            ],
        }
    )
    # STATICFILES_DIRS mirrors main.settings: computed from this file's
    # location rather than baked in at generation time.
    STATICFILES_DIRS: list[Any] = Field(
        default_factory=lambda: [str(_PROJECT_ROOT / "static")]
    )
    STATIC_ROOT: str = Field(default="staticfiles")
    # STATIC_URL is conditionally rewritten when CLOUDFRONT_DIST is set; see
    # _configure_static_url below.
    STATIC_URL: str = Field(default="/static/")
    STATUS_TOKEN: str = Field(default="")
    # TEMPLATES' DIRS entry mirrors main.settings: computed from this file's
    # location rather than baked in at generation time.
    TEMPLATES: list[Any] = Field(
        default_factory=lambda: [
            {
                "BACKEND": "django.template.backends.django.DjangoTemplates",
                "DIRS": [str(_PROJECT_ROOT) + "/templates/"],
                "APP_DIRS": True,
                "OPTIONS": {
                    "context_processors": [
                        "django.template.context_processors.debug",
                        "django.template.context_processors.request",
                        "django.contrib.auth.context_processors.auth",
                        "django.contrib.messages.context_processors.messages",
                        "social_django.context_processors.backends",
                        "social_django.context_processors.login_redirect",
                    ]
                },
            }
        ]
    )
    TIME_ZONE: str = Field(default="UTC")
    USE_I18N: bool = Field(default=True)
    USE_TZ: bool = Field(default=True)
    USE_X_FORWARDED_HOST: bool = Field(default=False)
    USE_X_FORWARDED_PORT: bool = Field(default=False)
    VERSION: str = Field(default="0.34.0")

    # ===== model_validators: derive complex settings from primitives =====
    # LOGGING is deliberately absent from this model: main.settings imports
    # it directly from mitol.observability.settings.logging rather than
    # building it, and the settings shim modules do the same.

    @model_validator(mode="after")
    def _configure_database(self) -> AqueductSettings:
        """Build DATABASES/DEFAULT_DATABASE_CONFIG from DATABASE_URL, mirroring
        the dj_database_url.parse(...) + CONN_MAX_AGE + SSL OPTIONS logic in
        main.settings.
        """
        config = dj_database_url.parse(self.DATABASE_URL)
        config["CONN_MAX_AGE"] = self.MITOL_DB_CONN_MAX_AGE
        config["OPTIONS"] = {} if self.MITOL_DB_DISABLE_SSL else {"sslmode": "require"}
        self.DEFAULT_DATABASE_CONFIG = config
        self.DATABASES = {"default": config}
        return self

    @model_validator(mode="after")
    def _configure_static_url(self) -> AqueductSettings:
        """Rewrite STATIC_URL to point at CLOUDFRONT_DIST when it is set."""
        if self.CLOUDFRONT_DIST:
            self.STATIC_URL = urljoin(
                f"https://{self.CLOUDFRONT_DIST}.cloudfront.net", self.STATIC_URL
            )
        return self

    @model_validator(mode="after")
    def _configure_conditional_apps(self) -> AqueductSettings:
        """Extend MIDDLEWARE/INSTALLED_APPS based on feature-flag and DEBUG env vars."""
        middleware = self.MIDDLEWARE
        installed_apps = self.INSTALLED_APPS
        if self.MIDDLEWARE_FEATURE_FLAG_QS_PREFIX:
            middleware = (
                *middleware,
                "main.middleware.feature_flags.QueryStringFeatureFlagMiddleware",
                "main.middleware.feature_flags.CookieFeatureFlagMiddleware",
            )
        if self.DEBUG:
            installed_apps = (*installed_apps, "debug_toolbar")
            middleware = (
                "debug_toolbar.middleware.DebugToolbarMiddleware",
                *middleware,
            )
        self.MIDDLEWARE = middleware
        self.INSTALLED_APPS = installed_apps
        return self

    @model_validator(mode="after")
    def _configure_celery_beat_schedule(self) -> AqueductSettings:
        """Build CELERY_BEAT_SCHEDULE with real crontab objects.

        crontab instances aren't natively serialisable by Pydantic, so this
        is computed after validation rather than kept as a plain field
        default.
        """
        self.CELERY_BEAT_SCHEDULE = {
            "delete_stale_chat_sessions": {
                "task": "ai_chatbots.tasks.delete_stale_sessions",
                "schedule": crontab(minute=0, hour=4),
            },
        }
        return self

    @model_validator(mode="after")
    def _configure_ai_model_defaults(self) -> AqueductSettings:
        """Apply the "defaults from a sibling setting" pattern used throughout
        the AI_* settings in main.settings (e.g. AI_MIT_SEARCH_URL defaults
        from AI_MIT_SEARCH_VECTOR_URL). Only applied when the field was not
        explicitly provided by an env var/init value.
        """
        fields_set = self.model_fields_set
        if "AI_DEFAULT_RECOMMENDATION_MODEL" not in fields_set:
            self.AI_DEFAULT_RECOMMENDATION_MODEL = self.AI_DEFAULT_MODEL
        if "AI_DEFAULT_SUMMARY_MODEL" not in fields_set:
            self.AI_DEFAULT_SUMMARY_MODEL = self.AI_DEFAULT_MODEL
        if "AI_DEFAULT_SYLLABUS_MODEL" not in fields_set:
            self.AI_DEFAULT_SYLLABUS_MODEL = self.AI_DEFAULT_MODEL
        if "AI_DEFAULT_VIDEO_GPT_MODEL" not in fields_set:
            self.AI_DEFAULT_VIDEO_GPT_MODEL = self.AI_DEFAULT_MODEL
        if "AI_MIT_SEARCH_URL" not in fields_set:
            self.AI_MIT_SEARCH_URL = self.AI_MIT_SEARCH_VECTOR_URL
        return self

    @model_validator(mode="after")
    def _configure_admins(self) -> AqueductSettings:
        """Build ADMINS from ADMIN_EMAIL, mirroring main.settings."""
        if self.ADMIN_EMAIL:
            self.ADMINS = (("Admins", self.ADMIN_EMAIL),)
        return self

    @model_validator(mode="after")
    def _configure_internal_ips(self) -> AqueductSettings:
        """Build INTERNAL_IPS from HOST_IP, mirroring main.settings."""
        self.INTERNAL_IPS = (self.HOST_IP,)
        return self

    @model_validator(mode="after")
    def _configure_redis_broker(self) -> AqueductSettings:
        """Resolve the REDIS_URL/REDISCLOUD_URL/CELERY_BROKER_URL fallback
        chain and propagate the result into CACHES["redis"]["LOCATION"].
        """
        self.REDIS_URL = self.REDIS_URL or self.REDISCLOUD_URL
        self.CELERY_BROKER_URL = self.CELERY_BROKER_URL or self.REDIS_URL
        self.CACHES["redis"]["LOCATION"] = self.CELERY_BROKER_URL
        return self

    @model_validator(mode="after")
    def _configure_channel_layers(self) -> AqueductSettings:
        """Build CHANNEL_LAYERS/REDIS_HOST_PARAMS from REDIS_DOMAIN and
        REDIS_SSL_CERT_REQS.
        """
        host_params = (
            {"ssl_cert_reqs": self.REDIS_SSL_CERT_REQS}
            if self.REDIS_SSL_CERT_REQS
            else {}
        )
        self.REDIS_HOST_PARAMS = host_params
        self.CHANNEL_LAYERS = {
            "default": {
                "BACKEND": "channels_redis.core.RedisChannelLayer",
                "CONFIG": {"hosts": [{"address": self.REDIS_DOMAIN, **host_params}]},
            },
        }
        return self

    @model_validator(mode="after")
    def _configure_anymail(self) -> AqueductSettings:
        """Build ANYMAIL from MAILGUN_KEY/MAILGUN_SENDER_DOMAIN."""
        self.ANYMAIL = {
            "MAILGUN_API_KEY": self.MAILGUN_KEY,
            "MAILGUN_SENDER_DOMAIN": self.MAILGUN_SENDER_DOMAIN,
        }
        return self

    @model_validator(mode="after")
    def _configure_jwt_auth(self) -> AqueductSettings:
        """Build JWT_AUTH from MITOL_JWT_SECRET/MITOL_COOKIE_NAME."""
        self.JWT_AUTH = {
            "JWT_SECRET_KEY": self.MITOL_JWT_SECRET,
            "JWT_VERIFY": True,
            "JWT_VERIFY_EXPIRATION": True,
            "JWT_EXPIRATION_DELTA": datetime.timedelta(seconds=60 * 60),
            "JWT_ALLOW_REFRESH": True,
            "JWT_REFRESH_EXPIRATION_DELTA": datetime.timedelta(days=7),
            "JWT_AUTH_COOKIE": self.MITOL_COOKIE_NAME,
            "JWT_AUTH_HEADER_PREFIX": "Bearer",
        }
        return self

    @model_validator(mode="after")
    def _configure_features(self) -> AqueductSettings:
        """Scan os.environ for MITOL_FEATURES_PREFIX-prefixed keys, mirroring
        main.settings' get_all_config_keys()-based FEATURES dict.
        """
        self.FEATURES = {
            key[len(self.MITOL_FEATURES_PREFIX) :]: get_bool(
                key, self.MITOL_FEATURES_DEFAULT
            )
            for key in os.environ
            if key.startswith(self.MITOL_FEATURES_PREFIX)
        }
        return self


class DevAqueductSettings(AqueductSettings):
    """Local-dev variant: fills missing values from Vault via OIDC instead of
    requiring a .env file.

    Env vars still take priority over Vault when explicitly set, so a developer
    can still override individual values locally.
    """

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls,
        init_settings,
        env_settings,
        dotenv_settings,  # noqa: ARG003
        file_secret_settings,  # noqa: ARG003
    ):
        """Prepend a Vault OIDC source, keeping init/env values authoritative."""
        import os

        from django_aqueduct.sources.vault import VaultSettingsSource

        # VAULT_AQUEDUCT_PATH and the "learn-ai" role default are
        # placeholders. The real values depend on how secrets are laid out
        # under the secret-learn-ai Vault mount today, which isn't
        # discoverable from this repo -- confirm against the live Vault
        # instance (e.g. `vault kv list secret-learn-ai/`) and set
        # VAULT_AQUEDUCT_PATH / VAULT_AQUEDUCT_ROLE accordingly, or hardcode
        # them here once confirmed.
        return (
            init_settings,
            env_settings,
            VaultSettingsSource(
                settings_cls,
                vault_url=os.environ["VAULT_ADDR"],
                vault_path=os.environ.get("VAULT_AQUEDUCT_PATH", ""),
                mount_point="secret-learn-ai",
                kv_version="2",
                auth_method="oidc",
                role=os.environ.get("VAULT_AQUEDUCT_ROLE", "learn-ai"),
            ),
        )
