# This file was generated by django-aqueduct (codegen v2).
# Regenerate with `manage.py generate_aqueduct_settings`.
#
# Code inside `# >>> aqueduct:generated:*` regions is overwritten on every run.
# Add validators and overrides inside `# >>> aqueduct:preserved:*` regions
# (or anywhere outside a generated region) — they survive regeneration.



"""Typed django-aqueduct settings model for main.settings.

The ``aqueduct:generated`` regions are machine-owned: they are produced by
``manage.py generate_aqueduct_settings`` (configured via ``[tool.aqueduct]``
in pyproject.toml) and rewritten on every regeneration. Hand-written
refinements live in the ``aqueduct:preserved:validators`` region and outside
the regions, and survive regeneration:

- Required fields main/settings.py enforces with ImproperlyConfigured
  (APP_BASE_URL, MAILGUN_KEY, MAILGUN_SENDER_DOMAIN, MITOL_COOKIE_NAME,
  MITOL_COOKIE_DOMAIN).
- Defaults restored for fields the generator redacted purely on a
  secret-looking *name* (e.g. *_MAX_TOKENS, CORS_ALLOW_CREDENTIALS).
- Primitives main/settings.py only reads inline, so static discovery cannot
  see them as settings (DATABASE_URL, MITOL_DB_*, REDISCLOUD_URL, HOST_IP,
  RUN_DATA_MIGRATIONS).
- @model_validator derivations for everything the generator marked DERIVED,
  built on django_aqueduct.derivations where a helper matches.

LOGGING is deliberately absent: the settings shims import it from
mitol.observability.settings.logging, exactly as main/settings.py does.

Deliberate divergences from main/settings.py are listed in
``[tool.aqueduct] parity_ignore`` and checked in CI via
``manage.py check_aqueduct_settings``.
"""

# >>> aqueduct:generated:imports
from __future__ import annotations

import ast
import json
import platform
from typing import Annotated, Any

from celery.schedules import crontab
from main.envs import get_string
from openapi.settings_spectacular import open_spectacular_settings
from pydantic import AliasChoices, Field, field_validator
from pydantic_settings import BaseSettings, NoDecode, SettingsConfigDict

# <<< aqueduct:generated:imports

# ---- hand-maintained imports (outside the generated region) ----
import datetime
import os
import pathlib
from urllib.parse import urljoin

from django.core.exceptions import ImproperlyConfigured
from django_aqueduct import derivations as dv
from django_aqueduct.sources.dev import vault_source_from_env
from pydantic import model_validator

# main/aqueduct_settings.py lives alongside main/settings.py, so this mirrors
# main.settings.BASE_DIR's two-levels-up-from-this-file computation.
_PROJECT_ROOT = pathlib.Path(__file__).resolve().parent.parent

class AqueductSettings(BaseSettings):
    """Typed Django settings model generated by django-aqueduct."""

    model_config = SettingsConfigDict(env_prefix="", extra="allow")

    # >>> aqueduct:generated:fields
    ADMINS: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    ADMIN_EMAIL: str = Field(
        default="",
        validation_alias=AliasChoices("MITOL_ADMIN_EMAIL"),
        description="e-mail configurable admins",
    )
    AI_ANON_LIMIT_MULTIPLIER: float = Field(
        default=10.0, validation_alias=AliasChoices("AI_ANON_LIMIT_MULTIPLIER")
    )
    AI_BUDGET_DURATION: str = Field(
        default="60m", validation_alias=AliasChoices("AI_BUDGET_DURATION")
    )
    AI_CHATBOTS_COOKIE_MAX_AGE: int = Field(
        default_factory=lambda: 24 * 60 * 60 * 7,
        validation_alias=AliasChoices("AI_CHATBOTS_COOKIE_MAX_AGE"),
    )
    AI_CHATBOTS_SESSION_EXPIRY_DAYS: int = Field(
        default=36500,
        validation_alias=AliasChoices("AI_CHATBOTS_SESSION_EXPIRY_DAYS"),
        description="AI settings",
    )
    AI_CITED_PROMPTS: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: [], validation_alias=AliasChoices("AI_CITED_PROMPTS")
    )
    AI_DEBUG: bool = Field(default=False, validation_alias=AliasChoices("AI_DEBUG"))
    AI_DEFAULT_MODEL: str = Field(
        default="openai/gpt-4o-mini", validation_alias=AliasChoices("AI_DEFAULT_MODEL")
    )
    AI_DEFAULT_RECOMMENDATION_MAX_TOKENS: int | None = Field(
        default=None,
        validation_alias=AliasChoices("AI_DEFAULT_RECOMMENDATION_MAX_TOKENS"),
    )  # REDACTED: name looks secret-like — set via a source, not here
    AI_DEFAULT_RECOMMENDATION_MODEL: str | None = Field(
        default=None, validation_alias=AliasChoices("AI_DEFAULT_RECOMMENDATION_MODEL")
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    AI_DEFAULT_SUMMARY_MODEL: str | None = Field(
        default=None, validation_alias=AliasChoices("AI_DEFAULT_SUMMARY_MODEL")
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    AI_DEFAULT_SYLLABUS_MAX_TOKENS: int | None = Field(
        default=None,
        validation_alias=AliasChoices("AI_DEFAULT_SYLLABUS_MAX_TOKENS"),
        description="AI agents that return lengthy tool/search results need larger token limits",  # noqa: E501
    )  # REDACTED: name looks secret-like — set via a source, not here
    AI_DEFAULT_SYLLABUS_MODEL: str | None = Field(
        default=None, validation_alias=AliasChoices("AI_DEFAULT_SYLLABUS_MODEL")
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    AI_DEFAULT_TEMPERATURE: float = Field(
        default=0.1, validation_alias=AliasChoices("AI_DEFAULT_TEMPERATURE")
    )
    AI_DEFAULT_TUTOR_MODEL: str = Field(
        default="openai/gpt-4o", validation_alias=AliasChoices("AI_DEFAULT_TUTOR_MODEL")
    )
    AI_DEFAULT_VIDEO_GPT_MAX_TOKENS: int | None = Field(
        default=None, validation_alias=AliasChoices("AI_DEFAULT_VIDEO_GPT_MAX_TOKENS")
    )  # REDACTED: name looks secret-like — set via a source, not here
    AI_DEFAULT_VIDEO_GPT_MODEL: str | None = Field(
        default=None, validation_alias=AliasChoices("AI_DEFAULT_VIDEO_GPT_MODEL")
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    AI_HUMAN_MAX_CONVERSATION_MEMORY: int = Field(
        default=6, validation_alias=AliasChoices("AI_HUMAN_MAX_CONVERSATION_MEMORY")
    )
    AI_INVERSE_METRICS: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: ["hallucination", "hallucinationmetric"],
        validation_alias=AliasChoices("AI_INVERSE_METRICS"),
    )
    AI_MAX_BUDGET: float = Field(
        default=0.05, validation_alias=AliasChoices("AI_MAX_BUDGET")
    )
    AI_MAX_MESSAGE_LENGTH: int = Field(
        default=6000, validation_alias=AliasChoices("AI_MAX_MESSAGE_LENGTH")
    )
    AI_MAX_PARALLEL_REQUESTS: int = Field(
        default=10, validation_alias=AliasChoices("AI_MAX_PARALLEL_REQUESTS")
    )
    AI_MAX_TOKEN_BIND: int | None = Field(
        default=None, validation_alias=AliasChoices("AI_MAX_TOKEN_BIND")
    )  # REDACTED: name looks secret-like — set via a source, not here
    AI_MIT_CONTENTFILE_URL: str = Field(
        default="https://api.learn.mit.edu/api/v1/contentfiles/",
        validation_alias=AliasChoices("AI_MIT_CONTENTFILE_URL"),
    )
    AI_MIT_CONTENT_SEARCH_LIMIT: int = Field(
        default=10, validation_alias=AliasChoices("AI_MIT_CONTENT_SEARCH_LIMIT")
    )
    AI_MIT_SEARCH_DETAIL_URL: str = Field(
        default="https://learn.mit.edu/?resource=",
        validation_alias=AliasChoices("AI_MIT_SEARCH_DETAIL_URL"),
        description="AI search settings",
    )
    AI_MIT_SEARCH_ELASTIC_URL: str = Field(
        default="https://api.learn.mit.edu/api/v1/learning_resources_search/",
        validation_alias=AliasChoices("AI_MIT_SEARCH_ELASTIC_URL"),
    )
    AI_MIT_SEARCH_LIMIT: int = Field(
        default=10, validation_alias=AliasChoices("AI_MIT_SEARCH_LIMIT")
    )
    AI_MIT_SEARCH_URL: str | None = Field(
        default=None, validation_alias=AliasChoices("AI_MIT_SEARCH_URL")
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    AI_MIT_SEARCH_VECTOR_URL: str = Field(
        default="https://api.learn.mit.edu/api/v0/vector_learning_resources_search/",
        validation_alias=AliasChoices("AI_MIT_SEARCH_VECTOR_URL"),
    )
    AI_MIT_SYLLABUS_URL: str = Field(
        default="https://api.learn.mit.edu/api/v0/vector_content_files_search/",
        validation_alias=AliasChoices("AI_MIT_SYLLABUS_URL"),
    )
    AI_MIT_TRANSCRIPT_SEARCH_LIMIT: int = Field(
        default=5, validation_alias=AliasChoices("AI_MIT_TRANSCRIPT_SEARCH_LIMIT")
    )
    AI_MIT_VIDEO_TRANSCRIPT_URL: str = Field(
        default="https://api.learn.mit.edu/api/v0/vector_content_files_search/",
        validation_alias=AliasChoices("AI_MIT_VIDEO_TRANSCRIPT_URL"),
    )
    AI_PROMPT_CACHE_DURATION: int = Field(
        default_factory=lambda: 60 * 60 * 24 * 28,
        validation_alias=AliasChoices("AI_PROMPT_CACHE_DURATION"),
    )
    AI_PROMPT_CACHE_FUNCTION: str = Field(
        default="ai_chatbots.utils.get_django_cache",
        validation_alias=AliasChoices("AI_PROMPT_CACHE_FUNCTION"),
    )
    AI_PROXY_AUTH_TOKEN: str | None = Field(
        default=None, validation_alias=AliasChoices("AI_PROXY_AUTH_TOKEN")
    )  # REDACTED: name looks secret-like — set via a source, not here
    AI_PROXY_CLASS: str = Field(
        default="",
        validation_alias=AliasChoices("AI_PROXY_CLASS"),
        description="AI proxy settings (aka LiteLLM)",
    )
    AI_PROXY_URL: str = Field(default="", validation_alias=AliasChoices("AI_PROXY_URL"))
    AI_RPM_LIMIT: int = Field(default=10, validation_alias=AliasChoices("AI_RPM_LIMIT"))
    AI_TPM_LIMIT: int = Field(
        default=5000, validation_alias=AliasChoices("AI_TPM_LIMIT")
    )
    AI_TUTOR_MAX_CONVERSATION_MEMORY: int = Field(
        default=6, validation_alias=AliasChoices("AI_TUTOR_MAX_CONVERSATION_MEMORY")
    )
    ALLOWED_HOSTS: Annotated[list[Any], NoDecode] = Field(default_factory=lambda: ["*"])
    ANONYMOUS_USER_NAME: Any = Field(
        default=None, description="Guardian\ndisable the anonymous user creation"
    )  # TODO: refine type
    ANYMAIL: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    APISIX_USERDATA_MAP: Annotated[dict[str, Any], NoDecode] = Field(
        default_factory=lambda: {
            "users_user": {
                "email": "email",
                "global_id": "sub",
                "username": "preferred_username",
                "name": "name",
            },
            "users_userprofile": {"country_code": None},
        },
        description="APISIX middleware settings",
    )
    APP_BASE_URL: str | None = Field(
        default=None, validation_alias=AliasChoices("MITOL_APP_BASE_URL")
    )
    ASGI_APPLICATION: str = Field(default="main.asgi.application")
    AUTHENTICATION_BACKENDS: tuple[Any, ...] = Field(
        default=(
            "django.contrib.auth.backends.ModelBackend",
            "guardian.backends.ObjectPermissionBackend",
        ),
        description="Social Auth configurations - [START]",
    )  # TODO: refine type
    AUTH_USER_MODEL: str = Field(
        default="users.User", description="Use the custom user model."
    )
    AWS_ACCESS_KEY_ID: str | None = Field(
        default=None, validation_alias=AliasChoices("AWS_ACCESS_KEY_ID")
    )  # REDACTED: name looks secret-like — set via a source, not here
    AWS_QUERYSTRING_AUTH: str = Field(
        default=False, validation_alias=AliasChoices("AWS_QUERYSTRING_AUTH")
    )
    AWS_SECRET_ACCESS_KEY: str | None = Field(
        default=None, validation_alias=AliasChoices("AWS_SECRET_ACCESS_KEY")
    )  # REDACTED: name looks secret-like — set via a source, not here
    AWS_STORAGE_BUCKET_NAME: str = Field(
        default=False, validation_alias=AliasChoices("AWS_STORAGE_BUCKET_NAME")
    )
    BASE_DIR: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CACHES: Any = Field(
        default=None, description="django cache back-ends"
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CANVAS_SYLLABUS_DEMO_READABLE_IDS: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: [],
        validation_alias=AliasChoices("CANVAS_SYLLABUS_DEMO_READABLE_IDS"),
    )
    CANVAS_TUTOR_DEMO_RUN_READABLE_IDS: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: [],
        validation_alias=AliasChoices("CANVAS_TUTOR_DEMO_RUN_READABLE_IDS"),
    )
    CELERY_BEAT_SCHEDULE: Any = Field(
        default_factory=lambda: {
    "delete_stale_chat_sessions": {
        "task": "ai_chatbots.tasks.delete_stale_sessions",
        "schedule": crontab(minute=0, hour=4),
    },
},
    )  # TODO: refine type
    CELERY_BROKER_URL: str | None = Field(
        default=None, validation_alias=AliasChoices("CELERY_BROKER_URL")
    )  # REDACTED: name looks secret-like — set via a source, not here
    CHANNEL_LAYERS: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CLOUDFRONT_DIST: str | None = Field(
        default=None, validation_alias=AliasChoices("CLOUDFRONT_DIST")
    )
    CONSUMER_THROTTLE_CLASSES: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: ["main.consumer_throttles.UserScopedRateThrottle"],
        validation_alias=AliasChoices("CONSUMER_THROTTLE_CLASSES"),
    )
    CORS_ALLOWED_ORIGINS: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: [],
        validation_alias=AliasChoices("CORS_ALLOWED_ORIGINS"),
    )
    CORS_ALLOWED_ORIGIN_REGEXES: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: [],
        validation_alias=AliasChoices("CORS_ALLOWED_ORIGIN_REGEXES"),
    )
    CORS_ALLOW_CREDENTIALS: bool | None = Field(
        default=None, validation_alias=AliasChoices("CORS_ALLOW_CREDENTIALS")
    )  # REDACTED: name looks secret-like — set via a source, not here
    CORS_ALLOW_HEADERS: tuple[Any, ...] = Field(
        default=(
            "accept",
            "authorization",
            "content-type",
            "user-agent",
            "x-csrftoken",
            "x-requested-with",
            "baggage",
            "sentry-trace",
        ),
    )  # TODO: refine type
    CORS_ALLOW_METHODS: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: ["POST", "OPTIONS"],
        validation_alias=AliasChoices("CORS_ALLOW_METHODS"),
    )
    CORS_ALLOW_ORIGINS: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: [],
        validation_alias=AliasChoices("CORS_ALLOW_ORIGINS"),
        description="CORS--- Used when initializing starlette.middleware.cors",
    )
    CSRF_COOKIE_DOMAIN: str | None = Field(
        default=None, validation_alias=AliasChoices("CSRF_COOKIE_DOMAIN")
    )
    CSRF_COOKIE_NAME: str = Field(
        default="csrftoken", validation_alias=AliasChoices("CSRF_COOKIE_NAME")
    )
    CSRF_COOKIE_SECURE: bool = Field(
        default=True, validation_alias=AliasChoices("CSRF_COOKIE_SECURE")
    )
    CSRF_HEADER_NAME: str = Field(
        default="HTTP_X_CSRFTOKEN", validation_alias=AliasChoices("CSRF_HEADER_NAME")
    )
    CSRF_TRUSTED_ORIGINS: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: [],
        validation_alias=AliasChoices("CSRF_TRUSTED_ORIGINS"),
    )
    DATABASES: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    DEBUG: bool = Field(
        default=False,
        validation_alias=AliasChoices("DEBUG"),
        description="SECURITY WARNING: don't run with debug turned on in production!",
    )
    DEFAULT_AUTO_FIELD: str = Field(default="django.db.models.AutoField")
    DEFAULT_DATABASE_CONFIG: Any = Field(
        default=None,
        description="Database\nhttps://docs.djangoproject.com/en/1.8/ref/settings/#databases\nUses DATABASE_URL to configure with sqlite default:\nFor URL structure:\nhttps://github.com/kennethreitz/dj-database-url",  # noqa: E501
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    DEFAULT_FROM_EMAIL: str = Field(
        default="webmaster@localhost", validation_alias=AliasChoices("MITOL_FROM_EMAIL")
    )
    EMAIL_BACKEND: str = Field(
        default="django.core.mail.backends.smtp.EmailBackend",
        validation_alias=AliasChoices("MITOL_EMAIL_BACKEND"),
        description="Configure e-mail settings",
    )
    EMAIL_HOST: str = Field(
        default="localhost", validation_alias=AliasChoices("MITOL_EMAIL_HOST")
    )
    EMAIL_HOST_PASSWORD: str | None = Field(
        default=None, validation_alias=AliasChoices("MITOL_EMAIL_PASSWORD")
    )  # REDACTED: name looks secret-like — set via a source, not here
    EMAIL_HOST_USER: str = Field(
        default="", validation_alias=AliasChoices("MITOL_EMAIL_USER")
    )
    EMAIL_PORT: int = Field(
        default=25, validation_alias=AliasChoices("MITOL_EMAIL_PORT")
    )
    EMAIL_SUPPORT: str = Field(
        default="support@example.com",
        validation_alias=AliasChoices("MITOL_SUPPORT_EMAIL"),
    )
    EMAIL_USE_TLS: bool = Field(
        default=False, validation_alias=AliasChoices("MITOL_EMAIL_TLS")
    )
    EMBEDLY_EMBED_URL: str = Field(
        default="https://api.embed.ly/1/oembed",
        validation_alias=AliasChoices("EMBEDLY_EMBED_URL"),
    )
    EMBEDLY_EXTRACT_URL: str = Field(
        default="https://api.embed.ly/1/extract",
        validation_alias=AliasChoices("EMBEDLY_EMBED_URL"),
    )
    EMBEDLY_KEY: str | None = Field(
        default=None,
        validation_alias=AliasChoices("EMBEDLY_KEY"),
        description="embed.ly configuration",
    )
    ENVIRONMENT: str = Field(
        default="dev", validation_alias=AliasChoices("MITOL_ENVIRONMENT")
    )
    EXTERNAL_MODELS: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: ["programcertificate"]
    )
    FEATURES: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    GA_G_TRACKING_ID: str = Field(
        default="", validation_alias=AliasChoices("GA_G_TRACKING_ID")
    )
    GA_TRACKING_ID: str = Field(
        default="", validation_alias=AliasChoices("GA_TRACKING_ID")
    )
    HEALTH_CHECK: Annotated[dict[str, Any], NoDecode] = Field(
        default_factory=lambda: {
            "SUBSETS": {
                "startup": [
                    "health_check.backends.MigrationsHealthCheck",
                    "health_check.cache.CacheBackend",
                    "health_check.backends.DatabaseBackend",
                ],
                "liveness": ["health_check.backends.DatabaseBackend"],
                "readiness": [
                    "health_check.cache.CacheBackend",
                    "health_check.backends.DatabaseBackend",
                ],
                "full": [
                    "health_check.backends.MigrationsHealthCheck",
                    "health_check.cache.CacheBackend",
                    "health_check.backends.DatabaseBackend",
                ],
            }
        },
    )
    HIJACK_ALLOW_GET_REQUESTS: bool = Field(default=True, description="Hijack")
    HIJACK_LOGOUT_REDIRECT_URL: str = Field(default="/admin/auth/user")
    HOSTNAME: Any = Field(
        default_factory=lambda: platform.node().split(".")[0]
    )  # TODO: refine type
    INSTALLED_APPS: tuple[Any, ...] = Field(
        default=(
            "django.contrib.admin",
            "django.contrib.auth",
            "django.contrib.contenttypes",
            "django.contrib.sessions",
            "django.contrib.messages",
            "django.contrib.staticfiles",
            "django.contrib.humanize",
            "django.contrib.sites",
            "django_filters",
            "django_scim",
            "rest_framework",
            "drf_spectacular",
            "oauth2_provider",
            "server_status",
            "anymail",
            "hijack",
            "hijack.contrib.admin",
            "guardian",
            "channels",
            "django_aqueduct",
            "mitol.observability.apps.ObservabilityConfig",
            "main",
            "openapi",
            "users",
            "ai_chatbots",
            "health_check",
            "health_check.cache",
        ),
    )  # TODO: refine type
    INTERNAL_IPS: Any = Field(
        default_factory=lambda: (get_string("HOST_IP", "127.0.0.1"),),
        description="Important to define this so DEBUG works properly",
    )  # TODO: refine type
    IPWARE_PRIVATE_IP_PREFIX: Any = Field(
        default=None,
        description="allow for all IPs to be routable, including localhost, for testing",  # noqa: E501
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    JWT_AUTH: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    KEYCLOAK_ADMIN_CLIENT_ID: str = Field(
        default=False,
        validation_alias=AliasChoices("KEYCLOAK_ADMIN_CLIENT_ID"),
        description="Keycloak API settings",
    )
    KEYCLOAK_ADMIN_CLIENT_SECRET: str | None = Field(
        default=None, validation_alias=AliasChoices("KEYCLOAK_ADMIN_CLIENT_SECRET")
    )  # REDACTED: name looks secret-like — set via a source, not here
    KEYCLOAK_ADMIN_SECURE: bool = Field(
        default=True, validation_alias=AliasChoices("KEYCLOAK_ADMIN_SECURE")
    )
    KEYCLOAK_ADMIN_URL: str = Field(
        default=False, validation_alias=AliasChoices("KEYCLOAK_ADMIN_URL")
    )
    KEYCLOAK_BASE_URL: str = Field(
        default="http://mit-keycloak-base-url.edu",
        validation_alias=AliasChoices("KEYCLOAK_BASE_URL"),
    )
    KEYCLOAK_REALM: str = Field(
        default=False, validation_alias=AliasChoices("KEYCLOAK_REALM")
    )
    KEYCLOAK_REALM_NAME: str = Field(
        default="olapps", validation_alias=AliasChoices("KEYCLOAK_REALM_NAME")
    )
    LANGSMITH_API_KEY: str | None = Field(
        default=None, validation_alias=AliasChoices("LANGSMITH_API_KEY")
    )  # REDACTED: name looks secret-like — set via a source, not here
    LANGUAGE_CODE: str = Field(default="en-us")
    LEARN_ACCESS_TOKEN: str | None = Field(
        default=None, validation_alias=AliasChoices("LEARN_ACCESS_TOKEN")
    )  # REDACTED: name looks secret-like — set via a source, not here
    MAILGUN_BCC_TO_EMAIL: str | None = Field(
        default=None, validation_alias=AliasChoices("MAILGUN_BCC_TO_EMAIL")
    )
    MAILGUN_FROM_EMAIL: str = Field(
        default="no-reply@example.com",
        validation_alias=AliasChoices("MAILGUN_FROM_EMAIL"),
    )
    MAILGUN_KEY: str | None = Field(
        default=None, validation_alias=AliasChoices("MAILGUN_KEY")
    )
    MAILGUN_RECIPIENT_OVERRIDE: str | None = Field(
        default=None, validation_alias=AliasChoices("MAILGUN_RECIPIENT_OVERRIDE")
    )
    MAILGUN_SENDER_DOMAIN: str | None = Field(
        default=None, validation_alias=AliasChoices("MAILGUN_SENDER_DOMAIN")
    )
    MEDIA_ROOT: str = Field(
        default="/var/media/", validation_alias=AliasChoices("MEDIA_ROOT")
    )
    MEDIA_URL: str = Field(default="/media/")
    MIDDLEWARE: tuple[Any, ...] = Field(
        default=(
            "django.middleware.security.SecurityMiddleware",
            "django.contrib.sessions.middleware.SessionMiddleware",
            "django.middleware.common.CommonMiddleware",
            "django.middleware.csrf.CsrfViewMiddleware",
            "django.contrib.auth.middleware.AuthenticationMiddleware",
            "main.middleware.apisix_user.ApisixUserMiddleware",
            "django.contrib.messages.middleware.MessageMiddleware",
            "django.middleware.clickjacking.XFrameOptionsMiddleware",
            "hijack.middleware.HijackUserMiddleware",
        ),
        description="OAuth2TokenMiddleware must be before SCIMAuthCheckMiddleware\nin order to insert request.user into the request.",  # noqa: E501
    )  # TODO: refine type
    MIDDLEWARE_FEATURE_FLAG_COOKIE_MAX_AGE_SECONDS: int = Field(
        default_factory=lambda: 60 * 60,
        validation_alias=AliasChoices("MIDDLEWARE_FEATURE_FLAG_COOKIE_MAX_AGE_SECONDS"),
    )
    MIDDLEWARE_FEATURE_FLAG_COOKIE_NAME: str = Field(
        default="MITOL_FEATURE_FLAGS",
        validation_alias=AliasChoices("MIDDLEWARE_FEATURE_FLAG_COOKIE_NAME"),
    )
    MIDDLEWARE_FEATURE_FLAG_QS_PREFIX: str | None = Field(
        default=None, validation_alias=AliasChoices("MIDDLEWARE_FEATURE_FLAG_QS_PREFIX")
    )
    MIGRATION_MODULES: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    MITOL_COOKIE_DOMAIN: str | None = Field(
        default=None, validation_alias=AliasChoices("MITOL_COOKIE_DOMAIN")
    )
    MITOL_COOKIE_NAME: str | None = Field(
        default=None, validation_alias=AliasChoices("MITOL_COOKIE_NAME")
    )
    MITOL_FEATURES_DEFAULT: bool = Field(
        default=False, validation_alias=AliasChoices("MITOL_FEATURES_DEFAULT")
    )
    MITOL_FEATURES_PREFIX: str = Field(
        default="FEATURE_", validation_alias=AliasChoices("MITOL_FEATURES_PREFIX")
    )
    MITOL_JWT_SECRET: str | None = Field(
        default=None,
        validation_alias=AliasChoices("MITOL_JWT_SECRET"),
        description="JWT authentication settings",
    )  # REDACTED: name looks secret-like — set via a source, not here
    MITOL_TITLE: str = Field(
        default="MIT Learn", validation_alias=AliasChoices("MITOL_TITLE")
    )
    MITOL_UNSUBSCRIBE_TOKEN_MAX_AGE_SECONDS: int | None = Field(
        default=None,
        validation_alias=AliasChoices("MITOL_UNSUBSCRIBE_TOKEN_MAX_AGE_SECONDS"),
    )  # REDACTED: name looks secret-like — set via a source, not here
    MITOL_USE_S3: bool = Field(
        default=False, validation_alias=AliasChoices("MITOL_USE_S3")
    )
    MIT_LEARN_API_PROXY_BASE_URL: str = Field(
        default="https://api.learn.mit.edu/api/",
        validation_alias=AliasChoices("MIT_LEARN_API_PROXY_BASE_URL"),
    )
    NOTIFICATION_ATTEMPT_CHUNK_SIZE: int = Field(default=100)
    NOTIFICATION_ATTEMPT_RATE_LIMIT: str = Field(default="600/m")
    NOTIFICATION_EMAIL_BACKEND: str = Field(
        default="anymail.backends.test.EmailBackend",
        validation_alias=AliasChoices("MITOL_NOTIFICATION_EMAIL_BACKEND"),
    )
    OPENAI_API_KEY: str | None = Field(
        default=None,
        validation_alias=AliasChoices("OPENAI_API_KEY"),
        description="Provider keys",
    )  # REDACTED: name looks secret-like — set via a source, not here
    OPENTELEMETRY_BATCH_SIZE: int = Field(
        default=512, validation_alias=AliasChoices("OPENTELEMETRY_BATCH_SIZE")
    )
    OPENTELEMETRY_ENDPOINT: str | None = Field(
        default=None, validation_alias=AliasChoices("OPENTELEMETRY_ENDPOINT")
    )
    OPENTELEMETRY_EXPORT_TIMEOUT_MS: int = Field(
        default=5000, validation_alias=AliasChoices("OPENTELEMETRY_EXPORT_TIMEOUT_MS")
    )
    OPENTELEMETRY_INSECURE: bool = Field(
        default=True, validation_alias=AliasChoices("OPENTELEMETRY_INSECURE")
    )
    OPENTELEMETRY_SERVICE_NAME: str = Field(
        default="learn-ai",
        validation_alias=AliasChoices("OPENTELEMETRY_SERVICE_NAME"),
        description="OpenTelemetry configuration (consumed by mitol-django-observability plugin).\nOTel is activated when OPENTELEMETRY_ENDPOINT (or OTEL_EXPORTER_OTLP_ENDPOINT\nenv var) is set, or when DEBUG=True. The old OPENTELEMETRY_ENABLED flag is no\nlonger supported; set OPENTELEMETRY_ENDPOINT to enable tracing.",  # noqa: E501
    )
    POSTHOG_API_HOST: str = Field(
        default="https://us.posthog.com",
        validation_alias=AliasChoices("POSTHOG_API_HOST"),
    )
    POSTHOG_PERSONAL_API_KEY: str | None = Field(
        default=None, validation_alias=AliasChoices("POSTHOG_PERSONAL_API_KEY")
    )  # REDACTED: name looks secret-like — set via a source, not here
    POSTHOG_PROJECT_API_KEY: str | None = Field(
        default=None, validation_alias=AliasChoices("POSTHOG_PROJECT_API_KEY")
    )  # REDACTED: name looks secret-like — set via a source, not here
    POSTHOG_PROJECT_ID: int | None = Field(
        default=None, validation_alias=AliasChoices("POSTHOG_PROJECT_ID")
    )
    POSTHOG_TIMEOUT_MS: int = Field(
        default=3000, validation_alias=AliasChoices("POSTHOG_TIMEOUT_MS")
    )
    PROBLEM_SET_URL: str = Field(
        default="https://api.learn.mit.edu/api/v0/tutor/problems/",
        validation_alias=AliasChoices("PROBLEM_SET_URL"),
    )
    QUERY_BATCH_SIZE: int = Field(
        default=500, validation_alias=AliasChoices("QUERY_BATCH_SIZE")
    )
    REACT_GA_DEBUG: bool = Field(
        default=False, validation_alias=AliasChoices("REACT_GA_DEBUG")
    )
    RECAPTCHA_SECRET_KEY: str | None = Field(
        default=None, validation_alias=AliasChoices("RECAPTCHA_SECRET_KEY")
    )  # REDACTED: name looks secret-like — set via a source, not here
    RECAPTCHA_SITE_KEY: str = Field(
        default="", validation_alias=AliasChoices("RECAPTCHA_SITE_KEY")
    )
    REDIS_DOMAIN: str = Field(
        default="redis://redis:6379/0",
        validation_alias=AliasChoices("REDIS_DOMAIN"),
        description="Channel settings",
    )
    REDIS_HOST_PARAMS: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    REDIS_SSL_CERT_REQS: str | None = Field(
        default=None, validation_alias=AliasChoices("REDIS_SSL_CERT_REQS")
    )
    REDIS_URL: str | None = Field(
        default=None, validation_alias=AliasChoices("REDIS_URL")
    )  # REDACTED: name looks secret-like — set via a source, not here
    REQUESTS_KEEPALIVE_EXPIRY: int = Field(
        default=180, validation_alias=AliasChoices("REQUESTS_KEEPALIVE_EXPIRY")
    )
    REQUESTS_TIMEOUT: int = Field(
        default=30, validation_alias=AliasChoices("REQUESTS_TIMEOUT")
    )
    REST_FRAMEWORK: Annotated[dict[str, Any], NoDecode] = Field(
        default_factory=lambda: {
            "DEFAULT_PERMISSION_CLASSES": (
                "rest_framework.permissions.IsAuthenticated",
            ),
            "DEFAULT_AUTHENTICATION_CLASSES": (
                "rest_framework.authentication.SessionAuthentication",
            ),
            "EXCEPTION_HANDLER": "main.exceptions.api_exception_handler",
            "TEST_REQUEST_DEFAULT_FORMAT": "json",
            "TEST_REQUEST_RENDERER_CLASSES": [
                "rest_framework.renderers.JSONRenderer",
                "rest_framework.renderers.MultiPartRenderer",
            ],
            "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
            "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.NamespaceVersioning",
            "ALLOWED_VERSIONS": ["v0"],
            "ORDERING_PARAM": "sortby",
        },
    )
    ROOT_URLCONF: str = Field(default="main.urls")
    SEARCH_PAGE_CACHE_DURATION: int = Field(
        default_factory=lambda: 60 * 60 * 24,
        validation_alias=AliasChoices("SEARCH_PAGE_CACHE_DURATION"),
    )
    SECRET_KEY: str | None = Field(
        default=None,
        validation_alias=AliasChoices("SECRET_KEY"),
        description="SECURITY WARNING: keep the secret key used in production secret!",
    )  # REDACTED: name looks secret-like — set via a source, not here
    SECURE_CROSS_ORIGIN_OPENER_POLICY: str = Field(
        default="same-origin",
        validation_alias=AliasChoices("SECURE_CROSS_ORIGIN_OPENER_POLICY"),
    )
    SECURE_PROXY_SSL_HEADER: tuple[Any, ...] = Field(
        default=("HTTP_X_FORWARDED_PROTO", "https"),
        description="Trust the X-Forwarded-Proto header set by the TLS-terminating proxy so Django\nrecognizes requests as already secure. Without this, SECURE_SSL_REDIRECT's True\ndefault sends every proxied request into an infinite redirect loop.",  # noqa: E501
    )  # TODO: refine type
    SECURE_REDIRECT_EXEMPT: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: [
            "^health/startup/$",
            "^health/liveness/$",
            "^health/readiness/$",
            "^health/full/$",
        ],
    )
    SECURE_SSL_REDIRECT: bool = Field(
        default=True, validation_alias=AliasChoices("MITOL_SECURE_SSL_REDIRECT")
    )
    SENTRY_DSN: str | None = Field(
        default=None,
        validation_alias=AliasChoices("SENTRY_DSN"),
        description="initialize Sentry before doing anything else so we capture any config errors",  # noqa: E501
    )  # REDACTED: name looks secret-like — set via a source, not here
    SENTRY_LOG_LEVEL: str = Field(
        default="ERROR", validation_alias=AliasChoices("SENTRY_LOG_LEVEL")
    )
    SENTRY_PROFILES_SAMPLE_RATE: float = Field(
        default=0, validation_alias=AliasChoices("SENTRY_PROFILES_SAMPLE_RATE")
    )
    SENTRY_TRACES_SAMPLE_RATE: float = Field(
        default=0, validation_alias=AliasChoices("SENTRY_TRACES_SAMPLE_RATE")
    )
    SESSION_COOKIE_DOMAIN: str | None = Field(
        default=None, validation_alias=AliasChoices("SESSION_COOKIE_DOMAIN")
    )
    SESSION_COOKIE_NAME: str = Field(
        default="sessionid", validation_alias=AliasChoices("SESSION_COOKIE_NAME")
    )
    SESSION_ENGINE: str = Field(
        default="django.contrib.sessions.backends.signed_cookies"
    )
    SITE_ID: int = Field(default=1)
    SPECTACULAR_SETTINGS: Any = Field(
        default_factory=lambda: open_spectacular_settings
    )  # TODO: refine type
    STATICFILES_DIRS: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    STATIC_ROOT: str = Field(default="staticfiles")
    STATIC_URL: str = Field(
        default="/static/",
        description="https://docs.djangoproject.com/en/1.8/howto/static-files/",
    )
    STATUS_TOKEN: str | None = Field(
        default=None, validation_alias=AliasChoices("STATUS_TOKEN")
    )  # REDACTED: name looks secret-like — set via a source, not here
    STORAGES: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    TEMPLATES: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    TIME_ZONE: str = Field(default="UTC")
    USE_I18N: bool = Field(default=True)
    USE_TZ: bool = Field(default=True)
    USE_X_FORWARDED_HOST: bool = Field(
        default=False, validation_alias=AliasChoices("USE_X_FORWARDED_HOST")
    )
    USE_X_FORWARDED_PORT: bool = Field(
        default=False, validation_alias=AliasChoices("USE_X_FORWARDED_PORT")
    )
    VERSION: str = Field(default="0.34.0")
    # <<< aqueduct:generated:fields

    # >>> aqueduct:generated:container_decoders
    @field_validator(
        "AI_CITED_PROMPTS",
        "AI_INVERSE_METRICS",
        "ALLOWED_HOSTS",
        "CANVAS_SYLLABUS_DEMO_READABLE_IDS",
        "CANVAS_TUTOR_DEMO_RUN_READABLE_IDS",
        "CONSUMER_THROTTLE_CLASSES",
        "CORS_ALLOWED_ORIGINS",
        "CORS_ALLOWED_ORIGIN_REGEXES",
        "CORS_ALLOW_METHODS",
        "CORS_ALLOW_ORIGINS",
        "CSRF_TRUSTED_ORIGINS",
        "EXTERNAL_MODELS",
        "SECURE_REDIRECT_EXEMPT",
        mode="before",
    )
    @classmethod
    def _aqueduct_decode_list_fields(cls, value: object) -> object:
        """Parse a list from a JSON, Python-literal, or comma-separated env string."""
        if not isinstance(value, str):
            return value
        try:
            parsed = json.loads(value)
        except (ValueError, TypeError):
            try:
                parsed = ast.literal_eval(value)
            except (ValueError, SyntaxError):
                parsed = None
        if isinstance(parsed, list):
            return parsed
        stripped = value.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            stripped = stripped[1:-1].strip()
        if not stripped:
            return []
        return [item.strip() for item in stripped.split(",")]

    @field_validator(
        "APISIX_USERDATA_MAP", "HEALTH_CHECK", "REST_FRAMEWORK", mode="before"
    )
    @classmethod
    def _aqueduct_decode_dict_fields(cls, value: object) -> object:
        """Parse a dict from a JSON or Python-literal env string."""
        if not isinstance(value, str):
            return value
        try:
            parsed = json.loads(value)
        except (ValueError, TypeError):
            parsed = None
        if isinstance(parsed, dict):
            return parsed
        return ast.literal_eval(value)

    # <<< aqueduct:generated:container_decoders

    # >>> aqueduct:preserved:validators
    # ---- field refinements (a later declaration overrides the generated one) --

    # Required: main.settings raises ImproperlyConfigured when these are unset.
    APP_BASE_URL: str = Field(validation_alias="MITOL_APP_BASE_URL")
    MAILGUN_KEY: str
    MAILGUN_SENDER_DOMAIN: str
    MITOL_COOKIE_NAME: str
    MITOL_COOKIE_DOMAIN: str

    # Redacted by the generator on a secret-looking *name* only; these are not
    # secrets — restore main.settings' real defaults.
    AI_DEFAULT_RECOMMENDATION_MAX_TOKENS: int = Field(default=7500)
    AI_DEFAULT_SYLLABUS_MAX_TOKENS: int = Field(default=16384)
    AI_DEFAULT_VIDEO_GPT_MAX_TOKENS: int = Field(default=16384)
    AI_MAX_TOKEN_BIND: int = Field(default=16384)
    MITOL_UNSUBSCRIBE_TOKEN_MAX_AGE_SECONDS: int = Field(default=604800)
    CORS_ALLOW_CREDENTIALS: bool = Field(default=True)

    # Redacted secrets whose legacy default is a (safe) placeholder or empty
    # string, not None — restore those defaults so behaviour matches
    # main/settings.py when the value is unset.
    SECRET_KEY: str = Field(default="terribly_unsafe_default_secret_key")
    MITOL_JWT_SECRET: str = Field(default="terribly_unsafe_default_jwt_secret_key")
    SENTRY_DSN: str = Field(default="")
    EMAIL_HOST_PASSWORD: str = Field(default="", validation_alias="MITOL_EMAIL_PASSWORD")
    OPENAI_API_KEY: str = Field(default="")
    POSTHOG_PROJECT_API_KEY: str = Field(default="")
    RECAPTCHA_SECRET_KEY: str = Field(default="")
    STATUS_TOKEN: str = Field(default="")
    LEARN_ACCESS_TOKEN: str = Field(default="")
    AI_PROXY_AUTH_TOKEN: str = Field(default="")

    # main.settings reads these with get_string(..., False); a bucket name is a
    # string, so model it honestly (parity_ignore documents the False/None
    # default mismatch).
    AWS_STORAGE_BUCKET_NAME: str | None = Field(default=None)

    # main.settings' get_string(..., False) idiom: False when unset, a string
    # when set. The generated `str = Field(default=False)` declarations fail
    # validation (pydantic-settings validates defaults), so widen to str | bool.
    AWS_QUERYSTRING_AUTH: str | bool = Field(default=False)
    KEYCLOAK_ADMIN_CLIENT_ID: str | bool = Field(default=False)
    KEYCLOAK_ADMIN_CLIENT_SECRET: str | bool = Field(default=False)
    KEYCLOAK_ADMIN_URL: str | bool = Field(default=False)
    KEYCLOAK_REALM: str | bool = Field(default=False)

    # main.settings reads these with get_float(..., 0), which returns the
    # *int* 0 default as-is when unset; keep that exact behaviour.
    SENTRY_TRACES_SAMPLE_RATE: float | int = Field(default=0)
    SENTRY_PROFILES_SAMPLE_RATE: float | int = Field(default=0)

    # main.settings' EMBEDLY_EXTRACT_URL intentionally reads the EMBEDLY_EMBED_URL
    # env var with a different default. pydantic 2.13 resolves both fields from a
    # shared validation_alias correctly, but two fields sharing an alias reads as
    # a collision. Drop the shared alias on the derived field (so it has no env of
    # its own) and reproduce the "reads the other's env var" quirk explicitly in
    # _configure_shared_env_aliases below — no ambiguity, same behaviour.
    # (AI_MIT_TRANSCRIPT_SEARCH_LIMIT no longer needs this: upstream #555 fixed it
    # to read its own AI_MIT_TRANSCRIPT_SEARCH_LIMIT env var.)
    EMBEDLY_EXTRACT_URL: str = Field(default="https://api.embed.ly/1/extract")

    # Primitives main/settings.py only reads inline (never assigns at module
    # level), so static discovery cannot see them; added by hand.
    DATABASE_URL: str = Field(
        default_factory=lambda: f"sqlite:///{_PROJECT_ROOT / 'db.sqlite3'}"
    )
    MITOL_DB_CONN_MAX_AGE: int = Field(default=0)
    MITOL_DB_DISABLE_SSL: bool = Field(default=False)
    REDISCLOUD_URL: str | None = Field(default=None)
    HOST_IP: str = Field(default="127.0.0.1")
    RUN_DATA_MIGRATIONS: bool = Field(default=False)

    # DERIVED fields re-typed; every one of these is populated by a validator
    # below (or carries a machine-independent default_factory replacing the
    # value the v1 generator froze at generation time).
    BASE_DIR: str = Field(default_factory=lambda: str(_PROJECT_ROOT))
    STATICFILES_DIRS: list[str] = Field(
        default_factory=lambda: [str(_PROJECT_ROOT / "static")]
    )
    TEMPLATES: list[dict[str, Any]] = Field(
        default_factory=lambda: [
            {
                "BACKEND": "django.template.backends.django.DjangoTemplates",
                "DIRS": [str(_PROJECT_ROOT) + "/templates/"],
                "APP_DIRS": True,
                "OPTIONS": {
                    "context_processors": [
                        "django.template.context_processors.debug",
                        "django.template.context_processors.request",
                        "django.contrib.auth.context_processors.auth",
                        "django.contrib.messages.context_processors.messages",
                        "social_django.context_processors.backends",
                        "social_django.context_processors.login_redirect",
                    ]
                },
            }
        ]
    )
    INTERNAL_IPS: tuple[Any, ...] = Field(default=("127.0.0.1",))
    ADMINS: tuple[Any, ...] = Field(default=())
    ANYMAIL: dict[str, Any] = Field(default_factory=dict)
    CACHES: dict[str, Any] = Field(default_factory=dict)
    CHANNEL_LAYERS: dict[str, Any] = Field(default_factory=dict)
    DATABASES: dict[str, Any] = Field(default_factory=dict)
    DEFAULT_DATABASE_CONFIG: dict[str, Any] = Field(default_factory=dict)
    FEATURES: dict[str, Any] = Field(default_factory=dict)
    JWT_AUTH: dict[str, Any] = Field(default_factory=dict)
    MIGRATION_MODULES: dict[str, Any] = Field(default_factory=dict)
    REDIS_HOST_PARAMS: dict[str, Any] = Field(default_factory=dict)
    STORAGES: dict[str, Any] = Field(default_factory=dict)

    # ---- validators: derive complex settings from primitives ----

    @model_validator(mode="after")
    def _configure_shared_env_aliases(self) -> AqueductSettings:
        """Reproduce main.settings' "read a sibling's env var" quirk.

        EMBEDLY_EXTRACT_URL has no env alias of its own; legacy reads it from
        EMBEDLY_EMBED_URL. When that source var is supplied, mirror it here;
        otherwise it keeps its own distinct default.
        """
        if "EMBEDLY_EMBED_URL" in self.model_fields_set:
            self.EMBEDLY_EXTRACT_URL = self.EMBEDLY_EMBED_URL
        return self

    @model_validator(mode="after")
    def _configure_database(self) -> AqueductSettings:
        """Build DATABASES/DEFAULT_DATABASE_CONFIG from DATABASE_URL.

        django_aqueduct.derivations.database_config wraps dj_database_url and
        applies sslmode=require only for non-SQLite backends (main/settings.py
        applies it unconditionally — a known bug this deliberately fixes).
        """
        config = dv.database_config(
            self.DATABASE_URL,
            conn_max_age=self.MITOL_DB_CONN_MAX_AGE,
            ssl_require=not self.MITOL_DB_DISABLE_SSL,
        )
        if self.MITOL_DB_DISABLE_SSL:
            # main/settings.py overwrites OPTIONS with {} in this branch.
            config["OPTIONS"] = {}
        self.DEFAULT_DATABASE_CONFIG = config
        self.DATABASES = {"default": config}
        return self

    @model_validator(mode="after")
    def _configure_redis_and_caches(self) -> AqueductSettings:
        """Resolve the REDIS_URL/REDISCLOUD_URL/CELERY_BROKER_URL fallback
        chain and build CACHES, mirroring main.settings.
        """
        self.REDIS_URL = dv.first_url(self.REDIS_URL, self.REDISCLOUD_URL)
        self.CELERY_BROKER_URL = dv.first_url(self.CELERY_BROKER_URL, self.REDIS_URL)
        self.CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
                "LOCATION": "local-in-memory-cache",
            },
            "external_assets": {
                "BACKEND": "django.core.cache.backends.db.DatabaseCache",
                "LOCATION": "external_asset_cache",
            },
            "durable": {
                "BACKEND": "django.core.cache.backends.db.DatabaseCache",
                "LOCATION": "durable_cache",
            },
            "redis": dv.redis_cache(
                self.CELERY_BROKER_URL,
                CLIENT_CLASS="django_redis.client.DefaultClient",
            ),
        }
        return self

    @model_validator(mode="after")
    def _configure_channel_layers(self) -> AqueductSettings:
        """Build CHANNEL_LAYERS/REDIS_HOST_PARAMS from REDIS_DOMAIN and
        REDIS_SSL_CERT_REQS.
        """
        self.REDIS_HOST_PARAMS = (
            {"ssl_cert_reqs": self.REDIS_SSL_CERT_REQS}
            if self.REDIS_SSL_CERT_REQS
            else {}
        )
        self.CHANNEL_LAYERS = {
            "default": {
                "BACKEND": "channels_redis.core.RedisChannelLayer",
                "CONFIG": {
                    "hosts": [
                        {"address": self.REDIS_DOMAIN, **self.REDIS_HOST_PARAMS}
                    ]
                },
            },
        }
        return self

    @model_validator(mode="after")
    def _configure_static_url(self) -> AqueductSettings:
        """Rewrite STATIC_URL to point at CLOUDFRONT_DIST when it is set."""
        if self.CLOUDFRONT_DIST:
            self.STATIC_URL = urljoin(
                f"https://{self.CLOUDFRONT_DIST}.cloudfront.net", self.STATIC_URL
            )
        return self

    @model_validator(mode="after")
    def _configure_internal_ips(self) -> AqueductSettings:
        """Build INTERNAL_IPS from HOST_IP, mirroring main.settings."""
        self.INTERNAL_IPS = (self.HOST_IP,)
        return self

    @model_validator(mode="after")
    def _configure_admins(self) -> AqueductSettings:
        """Build ADMINS from ADMIN_EMAIL, mirroring main.settings' fixed
        "Admins" label (fed through the derivations parser).
        """
        self.ADMINS = tuple(
            dv.admins_from_csv(
                f"Admins <{self.ADMIN_EMAIL}>" if self.ADMIN_EMAIL else None
            )
        )
        return self

    @model_validator(mode="after")
    def _configure_anymail(self) -> AqueductSettings:
        """Build ANYMAIL from MAILGUN_KEY/MAILGUN_SENDER_DOMAIN."""
        self.ANYMAIL = {
            "MAILGUN_API_KEY": self.MAILGUN_KEY,
            "MAILGUN_SENDER_DOMAIN": self.MAILGUN_SENDER_DOMAIN,
        }
        return self

    @model_validator(mode="after")
    def _configure_jwt_auth(self) -> AqueductSettings:
        """Build JWT_AUTH from MITOL_JWT_SECRET/MITOL_COOKIE_NAME."""
        self.JWT_AUTH = {
            "JWT_SECRET_KEY": self.MITOL_JWT_SECRET,
            "JWT_VERIFY": True,
            "JWT_VERIFY_EXPIRATION": True,
            "JWT_EXPIRATION_DELTA": datetime.timedelta(seconds=60 * 60),
            "JWT_ALLOW_REFRESH": True,
            "JWT_REFRESH_EXPIRATION_DELTA": datetime.timedelta(days=7),
            "JWT_AUTH_COOKIE": self.MITOL_COOKIE_NAME,
            "JWT_AUTH_HEADER_PREFIX": "Bearer",
        }
        return self

    @model_validator(mode="after")
    def _configure_ai_model_defaults(self) -> AqueductSettings:
        """Default the per-bot AI models from AI_DEFAULT_MODEL (and
        AI_MIT_SEARCH_URL from AI_MIT_SEARCH_VECTOR_URL) when unset,
        mirroring main.settings' "default from a sibling setting" pattern.
        """
        self.AI_DEFAULT_RECOMMENDATION_MODEL = (
            self.AI_DEFAULT_RECOMMENDATION_MODEL or self.AI_DEFAULT_MODEL
        )
        self.AI_DEFAULT_SUMMARY_MODEL = (
            self.AI_DEFAULT_SUMMARY_MODEL or self.AI_DEFAULT_MODEL
        )
        self.AI_DEFAULT_SYLLABUS_MODEL = (
            self.AI_DEFAULT_SYLLABUS_MODEL or self.AI_DEFAULT_MODEL
        )
        self.AI_DEFAULT_VIDEO_GPT_MODEL = (
            self.AI_DEFAULT_VIDEO_GPT_MODEL or self.AI_DEFAULT_MODEL
        )
        self.AI_MIT_SEARCH_URL = (
            self.AI_MIT_SEARCH_URL or self.AI_MIT_SEARCH_VECTOR_URL
        )
        return self

    @model_validator(mode="after")
    def _configure_conditional_apps(self) -> AqueductSettings:
        """Extend MIDDLEWARE/INSTALLED_APPS based on the feature-flag
        middleware prefix and DEBUG, mirroring main.settings.
        """
        middleware = tuple(self.MIDDLEWARE)
        installed_apps = tuple(self.INSTALLED_APPS)
        if self.MIDDLEWARE_FEATURE_FLAG_QS_PREFIX:
            middleware = (
                *middleware,
                "main.middleware.feature_flags.QueryStringFeatureFlagMiddleware",
                "main.middleware.feature_flags.CookieFeatureFlagMiddleware",
            )
        if self.DEBUG:
            installed_apps = (*installed_apps, "debug_toolbar")
            middleware = (
                "debug_toolbar.middleware.DebugToolbarMiddleware",
                *middleware,
            )
            # main.settings only defines this under DEBUG so that all IPs,
            # including localhost, are routable in local testing. When DEBUG is
            # off it stays None and is dropped from the injected settings by
            # model_dump below, so ipware falls back to its own default (matching
            # legacy, which leaves the name undefined) rather than seeing None.
            self.IPWARE_PRIVATE_IP_PREFIX = ()
        self.MIDDLEWARE = middleware
        self.INSTALLED_APPS = installed_apps
        return self

    @model_validator(mode="after")
    def _configure_migration_modules(self) -> AqueductSettings:
        """Disable the data_fixtures migrations unless RUN_DATA_MIGRATIONS is
        set — main.settings only defines MIGRATION_MODULES in that case, so
        the enabled branch degrades to Django's default ({}).
        """
        self.MIGRATION_MODULES = (
            {} if self.RUN_DATA_MIGRATIONS else {"data_fixtures": None}
        )
        return self

    def model_dump(self, *args: Any, **kwargs: Any) -> dict[str, Any]:
        """Drop IPWARE_PRIVATE_IP_PREFIX from the output when it is None.

        main.settings only defines IPWARE_PRIVATE_IP_PREFIX under DEBUG; when
        DEBUG is off the name is left undefined, so ``getattr`` in django-ipware
        returns ipware's own default. Injecting an explicit ``None`` instead
        would override that default. Omitting the key here keeps the injected
        settings (and the parity comparison) faithful to the legacy module.
        """
        data = super().model_dump(*args, **kwargs)
        if data.get("IPWARE_PRIVATE_IP_PREFIX") is None:
            data.pop("IPWARE_PRIVATE_IP_PREFIX", None)
        return data

    @model_validator(mode="after")
    def _configure_storages(self) -> AqueductSettings:
        """Validate the S3 configuration and build STORAGES.

        main.settings leaves STORAGES undefined when MITOL_USE_S3 is off; the
        model pins Django's documented defaults explicitly instead.
        """
        if self.MITOL_USE_S3:
            if not (
                self.AWS_ACCESS_KEY_ID
                and self.AWS_SECRET_ACCESS_KEY
                and self.AWS_STORAGE_BUCKET_NAME
            ):
                msg = (
                    "You have enabled S3 support, but are missing one of "
                    "AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, or "
                    "AWS_STORAGE_BUCKET_NAME"
                )
                raise ImproperlyConfigured(msg)
            self.STORAGES = {
                "default": {
                    "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
                },
                "staticfiles": {
                    "BACKEND": (
                        "django.contrib.staticfiles.storage.StaticFilesStorage"
                    ),
                },
            }
        else:
            self.STORAGES = {
                "default": {
                    "BACKEND": "django.core.files.storage.FileSystemStorage",
                },
                "staticfiles": {
                    "BACKEND": (
                        "django.contrib.staticfiles.storage.StaticFilesStorage"
                    ),
                },
            }
        return self

    @staticmethod
    def _parse_feature_flag(name: str, value: Any) -> Any:
        """Parse a feature-flag value like main.envs.get_bool does."""
        if isinstance(value, bool):
            return value
        if isinstance(value, str):
            lowered = value.strip().lower()
            if lowered == "true":
                return True
            if lowered == "false":
                return False
            msg = f"Expected value in {name}={value} to be a boolean"
            raise ImproperlyConfigured(msg)
        return bool(value)

    @model_validator(mode="after")
    def _configure_features(self) -> AqueductSettings:
        """Collect MITOL_FEATURES_PREFIX-prefixed flags into FEATURES.

        django_aqueduct.derivations.feature_flags reads the *model* (including
        ``extra`` values delivered by Vault/SSM sources), fixing the legacy
        os.environ-only scan that made Vault-supplied flags invisible. Flags
        set as plain environment variables are still honoured — pydantic does
        not surface undeclared env vars as extras, so the environment scan is
        kept as the lowest-precedence source.
        """
        prefix = self.MITOL_FEATURES_PREFIX
        flags = {
            key: value for key, value in os.environ.items() if key.startswith(prefix)
        }
        flags.update(dv.feature_flags(self, prefix=prefix, strip_prefix=False))
        self.FEATURES = {
            name[len(prefix) :]: self._parse_feature_flag(name, value)
            for name, value in flags.items()
        }
        return self
    # <<< aqueduct:preserved:validators

class DevAqueductSettings(AqueductSettings):
    """Local-dev variant: fills values missing from the environment from Vault.

    Vault is wired entirely from ``VAULT_*`` environment variables via
    django_aqueduct.sources.dev.vault_source_from_env:

    - ``VAULT_ADDR``         enables Vault; when unset the model runs without it
    - ``VAULT_PATH``         KV secret path (required once VAULT_ADDR is set)
    - ``VAULT_MOUNT``        KV mount point (e.g. ``secret-learn-ai``)
    - ``VAULT_KV_VERSION``   ``1`` or ``2`` (default ``2``)
    - ``VAULT_AUTH_METHOD``  ``token`` / ``oidc`` / ``kubernetes``
    - ``VAULT_TOKEN`` / ``VAULT_ROLE`` per auth method

    Misconfiguration raises an actionable VaultConfigError instead of the bare
    KeyError the previous hand-rolled source produced. The Vault source is
    appended *after* the standard sources so explicitly-set environment
    variables keep priority over Vault, matching the previous behaviour (note
    django_aqueduct's VaultDevBase prepends Vault instead, which would invert
    that precedence — hence the explicit hook here).
    """

    @classmethod
    def settings_customise_sources(  # noqa: PLR0913
        cls,
        settings_cls,
        init_settings,
        env_settings,
        dotenv_settings,
        file_secret_settings,
    ):
        """Append an env-configured Vault source when VAULT_ADDR is set."""
        base = (init_settings, env_settings, dotenv_settings, file_secret_settings)
        vault = vault_source_from_env(settings_cls)
        return (*base, vault) if vault is not None else base


def init_sentry_from_model(model: BaseSettings) -> None:
    """Initialize Sentry from the validated (but not yet injected) model.

    Passed as ``configure_django_settings``' ``pre_configure`` hook by the
    settings shims: it runs before Django settings exist -- matching
    main/settings.py's init-Sentry-first ordering so config errors are
    captured -- but *after* the model has resolved values through its source
    chain, so a Vault/SSM-supplied SENTRY_DSN works.
    """
    from main.sentry import init_sentry

    init_sentry(
        dsn=model.SENTRY_DSN,
        environment=model.ENVIRONMENT,
        version=model.VERSION,
        log_level=model.SENTRY_LOG_LEVEL,
        traces_sample_rate=model.SENTRY_TRACES_SAMPLE_RATE,
        profiles_sample_rate=model.SENTRY_PROFILES_SAMPLE_RATE,
    )
