# Generated by Django 4.2.18 on 2025-02-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DjLangCheckpointWrite",
            fields=[
                ("thread_id", models.TextField()),
                ("checkpoint_ns", models.TextField()),
                ("checkpoint_id", models.TextField()),
                ("task_id", models.TextField()),
                ("idx", models.IntegerField()),
                ("channel", models.TextField()),
                ("type", models.TextField(blank=True, null=True)),
                ("blob", models.BinaryField()),
                ("task_path", models.TextField()),
            ],
            options={
                "unique_together": {
                    ("thread_id", "checkpoint_ns", "checkpoint_id", "task_id", "idx")
                },
            },
        ),
        migrations.CreateModel(
            name="DjLangCheckpoint",
            fields=[
                ("thread_id", models.TextField()),
                ("checkpoint_ns", models.TextField()),
                ("checkpoint_id", models.TextField()),
                ("parent_checkpoint_id", models.TextField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
                ("checkpoint", models.BinaryField()),
                ("metadata", models.JSONField()),
            ],
            options={
                "unique_together": {("thread_id", "checkpoint_ns", "checkpoint_id")},
            },
        ),
    ]
