# Generated by Django 4.2.18 on 2025-02-09 11:50

from django.conf import settings
from django.db import migrations


def set_canvas_rate_limits(apps, schema_editor):
    """Populate initial rate limits for consumers"""
    ConsumerThrottleLimit = apps.get_model("main", "ConsumerThrottleLimit")
    ConsumerThrottleLimit.objects.get_or_create(
        throttle_key="canvas_syllabus_bot",
        defaults={
            "auth_limit": 1000,
            "anon_limit": 1000,
            "interval": "day",
        },
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            set_canvas_rate_limits, reverse_code=migrations.RunPython.noop
        )
    ]
