model_list:
  - model_name: "bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0"
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0
      aws_region_name: us-east-1
  - model_name: "*"
    litellm_params:
      model: openai/*
      api_key: os.environ/OPENAI_API_KEY


guardrails:
  - guardrail_name: "aporia-pre-guard"
    litellm_params:
      guardrail: aporia  # supported values: "aporia", "lakera"
      mode: "during_call"
      api_key: os.environ/APORIA_API_KEY
      api_base: os.environ/APORIA_API_URL
  - guardrail_name: "aporia-post-guard"
    litellm_params:
      guardrail: aporia  # supported values: "aporia", "lakera"
      mode: "post_call"
      api_key: os.environ/APORIA_API_KEY
      api_base: os.environ/APORIA_API_URL

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL

litellm_settings:
  # The following should set default customer budgets, but they are
  # being ignored or not created (not sure which).
  # https://docs.litellm.ai/docs/proxy/users#customers
  max_end_user_budget: os.environ/AI_MAX_BUDGET
  max_end_user_budget_duration: os.environ/AI_MAX_BUDGET_DURATION
