model_list:
  - model_name: "gpt-3.5-turbo"
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY
  - model_name: "gpt-4"
    litellm_params:
      model: openai/gpt-4
      api_key: os.environ/OPENAI_API_KEY
  - model_name: "gpt-4o"
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
  - model_name: "bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0"
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0
      aws_region_name: us-east-1

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

litellm_settings:
  # The following should set default customer budgets, but they are
  # being ignored or not created (not sure which).
  # https://docs.litellm.ai/docs/proxy/users
  max_end_user_budget: os.environ/OPENAI_AI_MAX_BUDGET
  max_end_user_budget_duration: os.environ/OPENAI_AI_MAX_BUDGET_DURATION
