upstreams:
  - id: 1
    nodes:
      "nginx:${{NGINX_PORT}}": 1
    type: roundrobin

routes:
  - id: 1
    name: "websocket"
    desc: "Special handling for websocket URLs."
    priority: 1
    upstream_id: 1
    enable_websocket: true
    plugins:
      openid-connect:
        client_id: ${{KEYCLOAK_CLIENT_ID}}
        client_secret: ${{KEYCLOAK_CLIENT_SECRET}}
        discovery: ${{KEYCLOAK_DISCOVERY_URL}}
        realm: ${{KEYCLOAK_REALM}}
        scope: ${{KEYCLOAK_SCOPES}}
        bearer_only: false
        introspection_endpoint_auth_method: "client_secret_post"
        ssl_verify: false
        session:
          secret: ${{APISIX_SESSION_SECRET_KEY}}
        logout_path: "/logout"
        post_logout_redirect_uri: ${{APISIX_LOGOUT_URL}}
        unauth_action: "pass"
      cors:
        allow_origins: "**"
        allow_methods: "**"
        allow_headers: "**"
        allow_credential: true
      response-rewrite:
        headers:
          set:
            Referrer-Policy: "origin"
    uris:
      - "/ws/*"
  - id: 2
    name: "passauth"
    desc: "Wildcard route that can use auth but doesn't require it."
    priority: 0
    upstream_id: 1
    plugins:
      openid-connect:
        client_id: ${{KEYCLOAK_CLIENT_ID}}
        client_secret: ${{KEYCLOAK_CLIENT_SECRET}}
        discovery: ${{KEYCLOAK_DISCOVERY_URL}}
        realm: ${{KEYCLOAK_REALM}}
        scope: ${{KEYCLOAK_SCOPES}}
        bearer_only: false
        introspection_endpoint_auth_method: "client_secret_post"
        ssl_verify: false
        session:
          secret: ${{APISIX_SESSION_SECRET_KEY}}
        logout_path: "/logout"
        post_logout_redirect_uri: ${{APISIX_LOGOUT_URL}}
        unauth_action: "pass"
      cors:
        allow_origins: "**"
        allow_methods: "**"
        allow_headers: "**"
        allow_credential: true
      response-rewrite:
        headers:
          set:
            Referrer-Policy: "origin"
    uri: "*"
  - id: 3
    name: "logout-redirect"
    desc: "Strip trailing slash from logout redirect."
    priority: 10
    upstream_id: 1
    uri: "/logout/*"
    plugins:
      redirect:
        uri: "/logout"
  - id: 4
    name: "reqauth"
    desc: "Routes that require authentication."
    priority: 10
    upstream_id: 1
    plugins:
      openid-connect:
        client_id: ${{KEYCLOAK_CLIENT_ID}}
        client_secret: ${{KEYCLOAK_CLIENT_SECRET}}
        discovery: ${{KEYCLOAK_DISCOVERY_URL}}
        realm: ${{KEYCLOAK_REALM}}
        scope: ${{KEYCLOAK_SCOPES}}
        bearer_only: false
        introspection_endpoint_auth_method: "client_secret_post"
        ssl_verify: false
        session:
          secret: ${{APISIX_SESSION_SECRET_KEY}}
        logout_path: "/logout"
        post_logout_redirect_uri: ${{APISIX_LOGOUT_URL}}
        unauth_action: "auth"
      cors:
        allow_origins: "**"
        allow_methods: "**"
        allow_headers: "**"
        allow_credential: true
      response-rewrite:
        headers:
          set:
            Referrer-Policy: "origin"
    uris:
      - "/admin/login/*"
      - "/http/login/"
#END
