# Generated by Django 4.2.18 on 2025-02-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chatbots', '0002_chat_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorBotOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.TextField()),
                ('chat_json', models.JSONField()),
            ],
        ),
    ]
