# Generated by Django 4.2.20 on 2025-04-09 19:36
import json
from pathlib import Path

from django.db import migrations, models


def populate_models(apps, schema_editor):
    """
    Populate the LLMModel table with initial data.
    """
    LLMModel = apps.get_model("ai_chatbots", "LLMModel")
    # Add any initial data you want to populate here
    with Path.open("ai_chatbots/fixtures/llm_models.json") as llm_json:
        for llm_model in json.load(llm_json):
            LLMModel.objects.get_or_create(
                provider=llm_model["provider"],
                name=llm_model["name"],
                litellm_id=llm_model["litellm_id"],
                enabled=llm_model["enabled"],
            )


class Migration(migrations.Migration):
    dependencies = [
        ("ai_chatbots", "0004_userchatsession_more_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMModel",
            fields=[
                (
                    "litellm_id",
                    models.CharField(max_length=512, primary_key=True, serialize=False),
                ),
                ("provider", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(default=True)),
            ],
        ),
        migrations.RunPython(populate_models, reverse_code=migrations.RunPython.noop),
    ]
