# Generated by Django 4.2.19 on 2025-03-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_chatbots", "0004_userchatsession_more_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userchatsession",
            name="agent",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="userchatsession",
            name="dj_session_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=512
            ),
        ),
        migrations.AlterField(
            model_name="userchatsession",
            name="object_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=256
            ),
        ),
        migrations.AlterField(
            model_name="userchatsession",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
