# Generated by Django 4.2.23 on 2025-07-17 16:36

import json

from django.db import migrations, models


def populate_tutorbotoutput_edx_module_id(apps, schema_editor):
    TutorBotOutput = apps.get_model("ai_chatbots", "TutorBotOutput")
    for tutorbot_output in TutorBotOutput.objects.all():
        json_data = json.loads(tutorbot_output.chat_json)
        tutorbot_output.edx_module_id = json_data.get("metadata", {}).get(
            "edx_module_id", ""
        )
        tutorbot_output.save()


class Migration(migrations.Migration):
    dependencies = [
        ("ai_chatbots", "0005_llmmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorbotoutput",
            name="edx_module_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(
            populate_tutorbotoutput_edx_module_id,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
