# Generated by Django 4.2.24 on 2025-09-17 11:52

import django.db.models.deletion
from django.db import migrations, models


def assign_sessions(apps, schema_editor):
    """Assign existing TutorBotOutput records to UserChatSessions"""
    TutorBotOutput = apps.get_model("ai_chatbots", "TutorBotOutput")
    UserChatSession = apps.get_model("ai_chatbots", "UserChatSession")

    for output in TutorBotOutput.objects.only("thread_id").iterator():
        session = UserChatSession.objects.filter(thread_id=output.thread_id).first()
        if session:
            output.session = session
            output.save(update_fields=["session"])
        else:
            # Delete the orphaned TutorBotOutput if no session found
            output.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("ai_chatbots", "0007_convert_tutorbot_to_checkpoints"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorbotoutput",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ai_chatbots.userchatsession",
            ),
        ),
        migrations.RunPython(assign_sessions, reverse_code=migrations.RunPython.noop),
    ]
