# Generated by Django 4.2.24 on 2025-09-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_chatbots", "0008_tutorbotoutput_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="djangocheckpoint",
            name="created_on",
            field=models.DateTimeField(null=True, default=None),
        ),
        migrations.AddField(
            model_name="tutorbotoutput",
            name="created_on",
            field=models.DateTimeField(null=True, default=None),
        ),
        migrations.AlterField(
            model_name="djangocheckpoint",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="tutorbotoutput",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
