# Generated by Django 4.2.24 on 2025-09-18 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_chatbots", "0009_djangocheckpoint_tutorbotoutput_created_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatResponseRating",
            fields=[
                (
                    "checkpoint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="rating",
                        serialize=False,
                        to="ai_chatbots.djangocheckpoint",
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("dislike", "Dislike"),
                            ("", "No Rating"),
                        ],
                        db_index=True,
                        max_length=10,
                        blank=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [models.Index(fields=["rating"], name="rating_value_idx")],
            },
        ),
    ]
