# Generated by Django 4.2.24 on 2025-09-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_chatbots", "0010_chatresponserating"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatresponserating",
            name="rating_reason",
            field=models.TextField(blank=True),
        ),
    ]
