# Generated by Django 4.2.27 on 2026-01-14 15:53

import json
from pathlib import Path

from django.db import migrations, models


def upsert_models(apps, schema_editor):
    """
    Populate the LLMModel table with initial data.
    """
    LLMModel = apps.get_model("ai_chatbots", "LLMModel")
    with Path.open("ai_chatbots/fixtures/initial_llm_models.json") as llm_json:
        for llm_model in json.load(llm_json):
            LLMModel.objects.update_or_create(
                litellm_id=llm_model["litellm_id"],
                defaults={
                    "provider": llm_model["provider"],
                    "name": llm_model["name"],
                    "enabled": llm_model["enabled"],
                    "temperature": llm_model.get("temperature", None),
                    "reasoning_effort": llm_model.get("reasoning_effort", ""),
                },
            )


class Migration(migrations.Migration):
    dependencies = [
        ("ai_chatbots", "0011_chatresponserating_rating_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmmodel",
            name="reasoning_effort",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="llmmodel",
            name="temperature",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.RunPython(upsert_models, reverse_code=migrations.RunPython.noop),
    ]
