# Generated by Django 5.2.17 on 2026-10-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_chatbots", "0012_llm_model_temp_reasoning"),
    ]

    operations = [
        migrations.AddField(
            model_name="userchatsession",
            name="support_ticket_reference",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
