# Generated by Django 5.2.17 on 2026-09-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_chatbots", "0012_llm_model_temp_reasoning"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryStoreItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("namespace", models.TextField(db_index=True)),
                ("key", models.TextField()),
                ("value", models.JSONField()),
            ],
            options={
                "unique_together": {("namespace", "key")},
            },
        ),
    ]
