# Generated by Django 5.2.17 on 2026-10-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_chatbots", "0013_support_ticket_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="userchatsession",
            name="support_ticket_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
